#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(TESTMEDICALIPFILEMANAGER_LIB)
#  define TESTMEDICALIPFILEMANAGER_EXPORT Q_DECL_EXPORT
# else
#  define TESTMEDICALIPFILEMANAGER_EXPORT Q_DECL_IMPORT
# endif
#else
# define TESTMEDICALIPFILEMANAGER_EXPORT
#endif
