#pragma once

#define SAFE_DELETE(a) { if( (a) != 0 ) delete (a); (a) = 0; }
#define SAFE_DELETES(a) { if( (a) != 0 ) delete [] (a); (a) = 0; }
#define SAFE_VTKDELETE(a) { if( (a) != 0 ) { (a)->Delete(); } }

// 소수점 자릿수 반올림
#define ROUNDING(x, dig)	( floor((x) * pow(float(10), dig) + 0.5f) / pow(float(10), dig) )

typedef unsigned char muint8;
typedef unsigned short muint16;
typedef unsigned int muint32;
typedef unsigned long long muint64;

typedef char mint8;
typedef short mint16;
typedef int mint32;
typedef long long mint64;
typedef unsigned char mask;
typedef unsigned char mask8;	// qt mask 함수때문에 선언에러 문제로 다시 선언

#define PRESET_MAX		100 // Total : 170. reserve default presets

#define RELEASE_DATE	__DATE__

#define RECENT_MAX		5

#define MASK_MAX		30
#define MESH_MAX		64
#define MASK_SECOND_MAX	6
#define VM_MASK0		(1)			// 
#define VM_MASK1		(1 << 1)	// 
#define VM_MASK2		(1 << 2)
#define VM_MASK3		(1 << 3)
#define VM_MASK4		(1 << 4)
#define VM_MASK5		(1 << 5)
#define VM_MASK6		(1 << 6)
#define VM_MASK7		(1 << 7)

#define SLIDER_RANGE	1000.0f
#define SLIDER_MID		SLIDER_RANGE/2

#define WINDOW_BOUNDING_DEPTH 5

#define FILE_NAME_RULE "[\\\\|\\/|:|\\*|\\?|\"|<|>|\\||]"

#define EXT_FILE_LIST "^(?i)(nii|raw|roi|txt|stl|obj|vtk|png|bmp|jpg|prd)$"

#define RUN_BY_UPDATER_INDICATOR						"run_by_updater"

#define DEEPCATCH_WHOLEBODY_MASKNAME_L3					"L3"
#define DEEPCATCH_WHOLEBODY_MASKNAME_L3_SLICE			"L3_Slice"
#define DEEPCATCH_WHOLEBODY_MASKNAME_ABDOMINAL_WAIST	"Abdominal Waist"
#define DEEPCATCH_WHOLEBODY_MASKNAME_SINGLE_SLICE		"Single_Slice"
#define DEEPCATCH_WHOLEBODY_MASKNAME_MULTI_SLICE		"Multi_Slice"
#define DEEPCATCH_WHOLEBODY_MASKNAME_SKIN				"Skin"
#define DEEPCATCH_WHOLEBODY_MASKNAME_BONE				"Bone"
#define DEEPCATCH_WHOLEBODY_MASKNAME_MUSCLE				"Muscle"
#define DEEPCATCH_WHOLEBODY_MASKNAME_AVF				"AVF"
#define DEEPCATCH_WHOLEBODY_MASKNAME_OF					"SF"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO					"IO"
#define DEEPCATCH_WHOLEBODY_MASKNAME_BSC				"CNS"
#define DEEPCATCH_WHOLEBODY_MASKNAME_AC					"Circumference"

// IO Classification.
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_LIVER			"Liver"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_GB				"GB"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_SPLEEN			"Spleen"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_LEFTKIDNEY		"Left Kidney"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_RIGHTKIDNEY		"Right Kidney"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_BLADDER			"Bladder"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_PANCREAS		"Pancreas"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_AORTA			"Aorta"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_AORTA_ARTERY	"Artery"
#define DEEPCATCH_WHOLEBODY_MASKNAME_IO_AORTA_VEIN		"Vein"

// muscle Classification.
#define DEEPCATCH_WHOLEBODY_MASKNAME_MUSCLE_ADP_TISSUE	"Muscle_adp_tissue"
#define DEEPCATCH_WHOLEBODY_MASKNAME_MUSCLE_ABNORMAL1	"Muscle_abnormal1"
#define DEEPCATCH_WHOLEBODY_MASKNAME_MUSCLE_ABNORMAL2	"Muscle_abnormal2"
#define DEEPCATCH_WHOLEBODY_MASKNAME_MUSCLE_NORMAL		"Muscle_normal"

// vertebra Classification.
#define DEEPCATCH_VERTEBRA_MASKNAME_BONE2VB		"Vertebral"
#define DEEPCATCH_VB_MASKNAME_L5	"L5"
#define DEEPCATCH_VB_MASKNAME_L4	"L4"
#define DEEPCATCH_VB_MASKNAME_L3	"L3"
#define DEEPCATCH_VB_MASKNAME_L2	"L2"
#define DEEPCATCH_VB_MASKNAME_L1	"L1"
#define DEEPCATCH_VB_MASKNAME_T1	"T1"
#define DEEPCATCH_VB_MASKNAME_T2	"T2"
#define DEEPCATCH_VB_MASKNAME_T3	"T3"
#define DEEPCATCH_VB_MASKNAME_T4	"T4"
#define DEEPCATCH_VB_MASKNAME_T5	"T5"
#define DEEPCATCH_VB_MASKNAME_T6	"T6"
#define DEEPCATCH_VB_MASKNAME_T7	"T7"
#define DEEPCATCH_VB_MASKNAME_T8	"T8"
#define DEEPCATCH_VB_MASKNAME_T9	"T9"
#define DEEPCATCH_VB_MASKNAME_T10	"T10"
#define DEEPCATCH_VB_MASKNAME_T11	"T11"
#define DEEPCATCH_VB_MASKNAME_T12	"T12"
#define DEEPCATCH_VB_MASKNAME_L3_DUP	"L3-dup0"
#define DEEPCATCH_VERTEBRA_MASKNAME_VB2BMCB_BM	"Bone marrow"
#define DEEPCATCH_VERTEBRA_MASKNAME_VB2BMCB_CB	"Cortical bone"
#define PROJNAME_BONE2VB	"Bone2VB_3DNN"
#define PROJNAME_VB2IND		"CT_VB2IND_3DNN"
#define PROJNAME_VB2BMCB	"CT_VB2BMCB_3DNN"
#define DEEPCATCH_DUPLICATION_MAX	20

// IO
#define PROJNAME_IO_CALSS		"IO_3Dnn"
#define PROJNAME_IO_AORTA_CALSS	"CT_VesselIO_3DNN"

// 
#define COMBO_ITEMNAME_ILIAC_CHEST	"waist(iliac crest)"
#define COMBO_ITEMNAME_LOWER_LIB	"waist(lower lib)"

// Mask
#define VB2IND_MASK_MAX 17
#define VB2BMCB_MASK_MAX 2
#define WB_NET_MASK_MAX 7
#define L3_ABDOMINAL_MASK_MAX 2
#define SINGLE_MULT_SLICT_MASK_MAX 2
#define EMPTY_MASK 1
#define VB_MASK_MAX (VB2IND_MASK_MAX + VB2BMCB_MASK_MAX + WB_NET_MASK_MAX + L3_ABDOMINAL_MASK_MAX + SINGLE_MULT_SLICT_MASK_MAX - EMPTY_MASK)

// Muscle Abdominal Classification.
#define MUSCLE_AB_PROJNAME	"CT_Muscle_Abdominal_3DNN"

// DeepCatch DOCTORANSWER Define
#define DEEPCATCH_HTMLNAME_DOCTORANSWER					"DeepCatch_Dotoranswer"

// DeepCatch trunk Predict Mode.
#define DEEPCATCH_MASKNAME_TRUNK						"Trunk"
#define DEEPCATCH_MASKNAME_ARMS							"Arms"

// DeepCatch QCT Predict Mode.
#define DEEPCATCH_MASKNAME_QCT_TRUNK					"QCT_Trunk"

#define DEEPCATCH_MACRO_CATEGORY_FILEPATH				"Path"
#define DEEPCATCH_MACRO_CATEGORY_TYPE					"Type"
#define DEEPCATCH_MACRO_CATEGORY_UNET					"UNET"
#define DEEPCATCH_MACRO_CATEGORY_CONTRAST				"Contrast"
#define DEEPCATCH_MACRO_CATEGORY_GENDER					"Gender"
#define DEEPCATCH_MACRO_CATEGORY_HEIGHT					"Height"
#define DEEPCATCH_MACRO_CATEGORY_WEIGHT					"Weight"
#define DEEPCATCH_MACRO_CATEGORY_SLICE					"Slice"
#define DEEPCATCH_MACRO_CATEGORY_IOCLASSIFICATION		"IOClassification"
#define DEEPCATCH_MACRO_CATEGORY_MUSCLEQUALITYMAP		"MuscleQualityMap"
#define DEEPCATCH_MACRO_CATEGORY_MACROTYPE				"MacroProcessType"
#define DEEPCATCH_MACRO_CATEGORY_THREADCOUNT			"ThreadCount"
#define DEEPCATCH_MACRO_CATEGORY_BODYCOMP				"BodyComposition"
#define DEEPCATCH_MACRO_CATEGORY_VERTEBRA				"Vertebra"
#define DEEPCATCH_MACRO_CATEGORY_LIVER_SPLEEN			"LiverSpleen"
#define DEEPCATCH_MACRO_CATEGORY_AORTA					"Aorta"
#define DEEPCATCH_MACRO_CATEGORY_VERTEBRAL				"Vertebral"

#define FUNCTION_USABLECOUNT_STATE_NORMAL				"normal"
#define FUNCTION_USABLECOUNT_STATE_REJECTED				"rejected"
#define FUNCTION_USABLECOUNT_STATE_UNLIMITED			"unlimited"
#define FUNCTION_USABLECOUNT_STATE_LIMITED				"limited"

enum DICOM_RESULT
{
	DR_ERROR = 0,
	DR_NORMAL = 1,
	DR_LOW_SPACING = 2,
};

enum MESH_REMESH_TYPE
{
	MESH_SOLID = 0,
	MESH_HOLLOW,
	MESH_REMESH,
	MESH_REDUCTION,
	MESH_SMOOTH,
	MESH_SUBDIVISION,
	MESH_ISLAND_FILTER
};

enum LAYER_RG_SHORTCUT
{
	LAYER_RG_NONE,
	LAYER_RG_CTRL,
	LAYER_RG_ALT,//REVERSE
	LAYER_RG_SHIFT,//Rolling ball
};

enum eAfterTHREAD
{
	THREAD_NONE = 0,
	THREAD_OPEN_FILE,
	THREAD_UPLOAD,
	THREAD_PREVIEW_MESHES,
	THREAD_TA_UPDATE,
	THREAD_EXPORT_FILES,
	THREAD_REBOOT,
	THREAD_BCKUP_TO_RAWS,
	THREAD_EXPORT_MESH_FILES,
	THREAD_SPLIT_TO_RAWS,
	THREAD_IMPORT_FILES,
	// DeepCatch MACRO DEV
	THREAD_DEEPDRAW_PREDICT,
	THREAD_CIRCUMFERENCE,
	THREAD_SAVE_CSV,

	// DeepCatch
	THREAD_L3_PREDICT,
	THREAD_L3_USERSELECT_PREDICT_BOTH,
	THREAD_L3_USERSELECT,
	THREAD_L3_CONFIRM,
	THREAD_ABDOMIAL_WAIST_RANGE,
	THREAD_ABDOMIAL_WAIST_CONFIRM,
	THREAD_ABDOMIAL_WAIST_USERSELECT,
	THREAD_SAVE_3D_VOLUME,
	THREAD_DEEPCATCH_REPORT,
	THREAD_TRUNK_PREDICT,						// trunk prediction.
	THREAD_TRUNK_PREDICT_APPLY,
	THREAD_QCT_PREDICT,							// QCT Predict
	THREAD_DEEPCATCH_DEEPDRAW_PREDICT,			// 
	THREAD_IO_CLASSIFICATION_PREDICT,			// IO predict.
	THREAD_IO_CLASSIFICATION_PREDICT2,			// Pancreas predict.
	THREAD_BONE2VB_PREDICT,						// 2022206_byPHS_ADD_VB_Net
	THREAD_VB2IND_PREDICT,						// 2022206_byPHS_ADD_VB_Net
	THREAD_VB2BMCB_PREDICT,						// 2022206_byPHS_ADD_VB_Net
	THREAD_IO_LIVER_SPLEEN_PREDICT,					// 202207_byPHS_liver/Spleen
	THREAD_IO_AORTA_PREDICT,					// 2022206_byPHS_ADD_VB_Net
	THREAD_L3_AORTA_NONE,
	THREAD_DEL_MASK_POSTERIOR,					// 2022206_byPHS_ADD

	THREAD_MUSCLE_CLASSIFICATION_ADP_TISSUE,	// macro muscle classification 1.
	THREAD_MUSCLE_CLASSIFICATION_ABNORMAL1,		// macro muscle classification 2.
	THREAD_MUSCLE_CLASSIFICATION_ABNORMAL2,		// macro muscle classification 3.
	THREAD_MUSCLE_CLASSIFICATION_NORMAL,		// macro muscle classification 4.

	// DeepCatch MACRO INNER
	THREAD_DEEPCATCH_PREDICT_OPTION,
	THREAD_DEEPCATCH_REPORT_START,
	THREAD_DEEPCATCH_SAVE_MIPD,
	THREAD_DEEPCATCH_NEXT_LOOP,

	// COVID19
	THREAD_COMPONENT_CHOICE,
	THREAD_PREDICT_PNEUMONIA,
	THREAD_CALCULATE_FEATURE,
	THREAD_REPORT_INSERT_RESULT,
	THREAD_VOLUME_PRESET,

	// 220408 허 건 과장(심장솔루션)
	THREAD_GMM_EXRACTMASK,

	///
	THREAD_MACRO_STEP0 = 20,
	THREAD_MACRO_STEP1,
	THREAD_MACRO_STEP2,
	THREAD_MACRO_STEP3,
	THREAD_MACRO_STEP4,
	THREAD_MACRO_STEP5,
	THREAD_MACRO_STEP6,
	THREAD_MACRO_STEP7,
	THREAD_MACRO_STEP8,
	THREAD_MACRO_STEP9,
	THREAD_MACRO_STEP10,
	THREAD_MACRO_STEP11,
	THREAD_MACRO_STEP12,
	THREAD_MACRO_STEP13,
	THREAD_MACRO_STEP14,
	THREAD_MACRO_STEP15,
	THREAD_MACRO_STEP16,
	THREAD_MACRO_STEP17,
	THREAD_MACRO_STEP18,
	THREAD_MACRO_STEP19,
	THREAD_MACRO_STEP20,
	THREAD_MACRO_STEP21,
	THREAD_MACRO_STEP22,
	THREAD_MACRO_STEP23,
	THREAD_MACRO_STEP24,
	THREAD_MACRO_STEP25,
	THREAD_MACRO_STEP26,
	THREAD_MACRO_STEP27,
	THREAD_MACRO_STEP28,
	THREAD_MACRO_STEP29,
	THREAD_MACRO_STEP30,
	THREAD_MACRO_STEP31,
	THREAD_MACRO_STEP32,
	THREAD_MACRO_STEP33,
	THREAD_MACRO_STEP34,
	THREAD_MACRO_STEP35,
	THREAD_MACRO_STEP36,
	THREAD_MACRO_STEP37,
	THREAD_MACRO_STEP38,
	THREAD_MACRO_STEP39,

	// Visual Printing
	THREAD_VISUAL_PRINT_PREVIEW_MESHES,	// Visual Print (Preview Meshes For Mesh Edit)
	THREAD_VISUAL_PRINT_SAVE_MESHES,	// Visual Print (Save Meshes For Mesh Edit)
	THREAD_VISUAL_PRINT_UPLOAD,			// Visual Print (STL File Upload)
	THREAD_VISUAL_PRINT_UPLOAD_ROI,		// Visual Print (MESH ROI File Upload)
	THREAD_VISUAL_PRINT_RUN,			// Visual Print (Run Modip Web browser)
//	THREAD_VISUAL_PRINT_MESH,	
	THREAD_VISUAL_PRINT_DIALOG,			// Visual Print Popup Dialog Run

	// Import Data
	THREAD_OPEN_IMPORT_DATA,

	THREAD_MEDIP_MACRO_EXPORT_MASK_RAW_FILES,
	THREAD_MEDIP_MACRO_EXPORT_MASK_NII_FILES,
	THREAD_MEDIP_MACRO_END,
};

enum MEDIP_ERR
{
	ERR_SUCCESS = 0,
	ERR_EXIST,
	ERR_REBOOT_FAIL,
	ERR_RENDER_INIT_FAIL,
	ERR_RESOURCE_INIT_FAIL,
	ERR_APP_INIT_FAIL,
	ERR_APP_PASSWORD_FAIL,
	ERR_INVALID_LICENSE,
	ERR_INTERNET_CONNECT_FAIL,
	ERR_FUNC_THREAD_EXIST = 20,
	ERR_FUNC_THREAD_FAIL,
	ERR_FUNC_INVALID_PARAM,
	ERR_FUNC_NEED_LICENSE,
	ERR_FUNC_OUT_OF_MEMORY,
	ERR_FUNC_CANCEL,
	ERR_FUNC_NOT_SELECTED,
	ERR_FUNC_UNSUPPORT,
	ERR_BREAK_RULE = 40,
	ERR_FILE_SAVE_FAIL = 60,
	ERR_FILE_LOAD_UNSUPPORT,
	ERR_FILE_LOAD_FAIL,

	ERR_UNKNOWN,
};

enum IMPORT_FILES
{
	IM_FILES_NONE = -1,
	IM_FILES_PRD = 0,
	IM_FILES_STL,
	IM_FILES_OBJ,
	IM_FILES_RAW,
	IM_FILES_NII,
	IM_FILES_TXT,
	IM_FILES_JPG,
	IM_FILES_PNG,
	IM_FILES_BMP,
	IM_FILES_3MF
};

enum EXPORT_FILES //for layer export files
{
	EX_FILES_NONE = -1,

	/////////////////////////
	//3D format Files first//
	/////////////////////////
	EX_FILES_STL = 0,
	EX_FILES_OBJ,
	EX_FILES_VTK,
	EX_FILES_3MF, 
	EX_FILES_USD, 

	////////////////////////
	//ROI Files & HU Files//
	////////////////////////
	EX_FILES_RAW,
	EX_FILES_HU_RAW,
	EX_FILES_NII,
	EX_FILES_HUNII,
	EX_FILES_COORDINATE_NII,
	EX_FILES_TXT,
};

enum EXPORT_3D_SURFACE_MESH_METHOD
{
	FIT_VOXEL_SIZE,
	CONTOURE_FILTER
};

enum PLAYBACK_MODE
{
	NONE,
	SINGLE_MODE,
	START_RECURSIVE_MODE,
	END_RECURSIVE_MODE,
};

enum LAYER_COLUMN_AKA
{
	L_COL_ALPHA = 0,
	L_COL_COLOR,
	L_COL_SHOW,
	//L_COL_MESH,
	L_COL_AI,
	L_COL_NAME,
	L_COL_COUNT,
};

enum MESH_COLUMN_AKA
{
	M_COL_SUB = 0,
	M_COL_COLOR,
	M_COL_SHOW,
	M_COL_NAME,
	M_COL_MATERIAL,
	M_COL_LOCK,
	M_COL_COUNT,
};


enum TA_RESULT_MAJOR_COLUMN
{
	TRMA_COL_SUB = 0,
	TRMA_COL_VISIBLE,
	TRMA_COL_NAME,
	TRMA_COL_BTN_AND_VALUE,
};

enum HOME_POSITION
{
	HP_ANTERIOR = 0,
	HP_POSTERIOR,
	HP_RIGHT,
	HP_LEFT,
	HP_SUPERIOR,
	HP_INFERIOR,
};

enum MAINTAB_TYPE
{
	MAINTAB_SEGMENTATION = 0,
	MAINTAB_MEASUREMENT,
	MAINTAB_TA, //Textrue analysis, Radiomics로 변경
	MAINTAB_REPORT,
	MAINTAB_MESH_EDITING,
	MAINTAB_COUNT,
	MAINTAB_VISUAL_PRINT_MESH_EDITING,
};

enum ANNOTATION_TYPE
{
	AT_NONE,
	AT_TEXT,
	AT_LEN,
	AT_ANGLE,
	AT_OVAL,	// 안씀
	AT_ARROW,
	AT_RECTANGLE,
	AT_PT_LINE,
	AT_NAME,		// 210817 허 건 과장 추가
	AT_ALL,
};

enum ANNOTATION_DRAWING_VIEWER_TYPE
{
	ADV_MPR_PLANE_WINDOW_VIEWER,
	ADV_MPR_PLANE_MEASUREMENT_VIEWER,
	ADV_MEASUREMENT_VOLUME_VIEWER,
	ADV_VOLUME_VIEWER,
};

enum SHADER_QUALITY
{
	SQ_INVISIBLE = 0,
	SQ_LOW,
	SQ_MIDDLE,
};

enum HESSIAN_EXTRACTOR_TYPE
{
	HESSIAN_VESSEL,
	HESSIAN_FISSURE,
};

enum WINDOW_TYPE
{
	WT_NONE,
	WT_VOLUME,
	WT_SEGMENT,
	WT_RESULT,
	WT_AXIAL,
	WT_CORONAL,
	WT_SAGITTAL,
	WT_SUB
};

enum SCULPT_MODE
{
	SM_SMOOTH,
	SM_INFLATE,
	SM_DEFLATE,
	SM_REDUCE,
	SM_REMESH,
	SM_MOVE,	
	SM_DRAG,
	SM_REFINE,
};

enum SELECT_MODE
{
	SM_VOLUME,
	SM_SURFACE,
};

enum SMOOTH_METHOD
{
	SMM_LAPLACIAN = 0,
	SMM_HC_LAPLACIAN = 1,
	SMM_LAPLACIAN_TAUBIN = 2,
	SMM_INFLATE = 3,
};

enum REDUCE_METHOD
{
	RM_PERCENTAGE = 0,
	RM_TRICOUNT = 1,
	RM_MAXDEVIATION = 2,
};

enum MESH_WORK_MODE
{
	MESH_WORK_NONE = 0,
	MESH_WORK_INTERSECT,
	MESH_WORK_DIFF,
	MESH_WORK_UNION,
	MESH_WORK_FOR_SINGLE, //not used
	MESH_WORK_PLANE_CUT,
	MESH_WORK_POLYGON_CUT,
	MESH_WORK_POLYLINE_CUT,	
	MESH_WORK_FREEPOLYLINE_CUT,
	MESH_WORK_DISTANCE,
	MESH_WORK_BRUSH_SELECTION,
	MESH_WORK_BRUSH_SCULPT,
	MESH_WORK_SMOOTH,
	MESH_WORK_REDUCTION,
	MESH_WORK_HOLLOW,
	MESH_WORK_REMESH,
	MESH_WORK_SOLID,
	MESH_WORK_FIND_HOLE,
	MESH_WORK_HOLE_FILL_SELECTED,
	MESH_WORK_MANIFULATE,
	MESH_WORK_TRANSFORM,
	MESH_WORK_SUBDIVISION,
	MESH_WORK_ISLANDFILTER,
	MESH_WORK_ATTACH,
	MESH_WORK_DUPLICATE,
	MESH_WORK_STAMP3D,
	MESH_WORK_MESHOFFSET,
	MESH_WORK_SHADER,
	//VISUAL_PRINT_MESH_WORK_NONE,
};


enum WORK_MODE
{
	WORK_NONE = 0,
	WORK_POLYROI,
	WORK_REGION_ROI,
	WORK_PICKERROI,
	WORK_SKETCHDRAWSEGMENTATION,
	WORK_SEED_SELECT,
	WORK_ANNOTATION,
	WORK_ANNOTATION_TEXT,
	WORK_ANNOTATION_PATH,
	WORK_ANNOTATION_PATH_PLAY,
	WORK_PATCHY_SELECT,
	WORK_WORKING_REGION_MOVE,
	WORK_CAPTURE,
	WORK_OVALROI,
	WORK_RECTROI,
	WORK_3D_CURVE_SPLIT,
	WORK_3D_PLANE_SPLIT,
	WORK_3D_ANGLE_SPLIT,
};

enum ANAL_WORK_MODE
{
	ANAL_WORK_NONE = 0,
	ANAL_WORK_ANNO_LENGTH,
	ANAL_WORK_ANNO_TEXT,
	ANAL_WORK_ANNO_ANGLE,
	ANAL_WORK_ANNO_ARROW,
	ANAL_WORK_ANNO_RECTANGLE,
	ANAL_WORK_ANNO_PROFILE_LINE,
	ANAL_WORK_SEGMENT_FREEDRAW,
	ANAL_WORK_SEGMENT_CALC_DISTANCE,
	ANAL_WORK_SEGMENT_POLY,
	ANAL_WORK_SEGMENT_PICKER,
	ANAL_WORK_SEGMENT_RECT,
	ANAL_WORK_SEGMENT_OVAL,
	ANAL_WORK_CAPTURE,
	ANAL_WORK_SKETCHDRAWSEGMENTATION,
	ANAL_WORK_3D_CURVE_SPLIT,
	ANAL_WORK_3D_PLANE_SPLIT,
	ANAL_WORK_PATH,
	ANAL_WORK_PATH_3D_PLAY,
};

enum RADIOMICS_WORK_MODE
{
	RADIOMICS_WORK_NONE = 0,
	RADIOMICS_WORK_ANNO_RECTANGLE,
};

enum THRESHOLD_WORK_MODE : uint16_t
{
	THRESHOLD_WORK_NONE = 0x0000,
	THRESHOLD_WORK_WITHIN_SELECTED_LAYER = 0x0001,
	THRESHOLD_WORK_WITHIN_BRUSH = 0x0002,
	THRESHOLD_WORK_SHOW_PREVIEW = 0x0004,
};
Q_DECLARE_FLAGS(THRESHOLD_WORK_MODES, THRESHOLD_WORK_MODE)

enum VISUAL_PRINT_WORK_MODE
{
	VISUAL_PRINT_MESH_WORK_NONE = 0,
	VISUAL_PRINT_MESH_WORK_INTERSECT,
	VISUAL_PRINT_MESH_WORK_DIFF,
	VISUAL_PRINT_MESH_WORK_UNION,
	VISUAL_PRINT_MESH_WORK_FOR_SINGLE, //not used
	VISUAL_PRINT_MESH_WORK_PLANE_CUT,
	VISUAL_PRINT_MESH_WORK_POLYGON_CUT,
	VISUAL_PRINT_MESH_WORK_POLYLINE_CUT,
	VISUAL_PRINT_MESH_WORK_DISTANCE,
	VISUAL_PRINT_MESH_WORK_FREEPOLYLINE_CUT,	
	VISUAL_PRINT_ANAL_WORK_LENGTH,
	VISUAL_PRINT_ANAL_WORK_TEXT,
	VISUAL_PRINT_ANAL_WORK_ANGLE,
	VISUAL_PRINT_ANAL_WORK_OVAL,
	VISUAL_PRINT_ANAL_WORK_ARROW,
	VISUAL_PRINT_ANAL_WORK_LINE,
	VISUAL_PRINT_ANAL_WORK_DRAW,
	VISUAL_PRINT_ANAL_WORK_POLY,
	VISUAL_PRINT_ANAL_WORK_CAPTURE,
	VISUAL_PRINT_ANAL_WORK_PICKER,
	VISUAL_PRINT_ANAL_WORK_RECT,
	VISUAL_PRINT_ANAL_WORK_SKETCHDRAWSEGMENTATION,
	VISUAL_PRINT_ANAL_WORK_3D_SPLIT,
	VISUAL_PRINT_ANAL_WORK_3D_PLANE_CUT,
	VISUAL_PRINT_ANAL_WORK_PATH,
	VISUAL_PRINT_ANAL_WORK_PATH_3D_PLAY,
};


enum MOUSE_ACTION_MODE
{
	MAM_NONE = 0x0000,
	MAM_BOUNDING_MINX_OVER = 0x0001,
	MAM_BOUNDING_MINY_OVER = 0x0002,
	MAM_BOUNDING_MAXX_OVER = 0x0004,
	MAM_BOUNDING_MAXY_OVER = 0x0008,
	MAM_BOUNDING_MOVE = 0x0010,
	MAM_BOUNDING_MINX_MOVE = 0x0020,
	MAM_BOUNDING_MINY_MOVE = 0x0040,
	MAM_BOUNDING_MAXX_MOVE = 0x0080,
	MAM_BOUNDING_MAXY_MOVE = 0x0100,
};

inline MOUSE_ACTION_MODE operator~(MOUSE_ACTION_MODE a)
{
	return static_cast<MOUSE_ACTION_MODE>(~static_cast<int>(a));
}

inline MOUSE_ACTION_MODE operator|(MOUSE_ACTION_MODE a, MOUSE_ACTION_MODE b)
{
	return static_cast<MOUSE_ACTION_MODE>(static_cast<int>(a) | static_cast<int>(b));
}

inline MOUSE_ACTION_MODE & operator|=(MOUSE_ACTION_MODE& a, MOUSE_ACTION_MODE b)
{
	a = a | b;
	return a;
}

inline MOUSE_ACTION_MODE operator&(MOUSE_ACTION_MODE a, MOUSE_ACTION_MODE b)
{
	return static_cast<MOUSE_ACTION_MODE>(static_cast<int>(a) & static_cast<int>(b));
}
inline MOUSE_ACTION_MODE & operator&=(MOUSE_ACTION_MODE& a, MOUSE_ACTION_MODE b)
{
	a = a & b;
	return a;
}

enum SLICE_PRESET
{
	SP_DEFAULT = 0,
	SP_RECOMMAND_1,
	SP_RECOMMAND_2,
	SP_BONE,
	SP_LUNG,
	SP_MEDIASTINAL,
	SP_BRAIN,
	SP_ABD,
	SP_LIVER,
	SP_KIDNEY,
	SP_URINARY_TRACK_BLADDER,
	SP_CUSTOM,
	SP_COUNT,
};

enum WINDOW2D_POSTPROCESS_FILTER
{
	W2PPF_NONE = 0,
	W2PPF_SHARPEN,
	W2PPF_SOFT,
	W2PPF_GAUSSIAN,
	W2PPF_SOBEL,
	W2PPF_CONTOURS,
};


enum WINDOW2D_THICKNESS
{
	W2PTK_00MM = 0,
	W2PTK_05MM,
	W2PTK_10MM,
	W2PTK_15MM,
	W2PTK_20MM,
	W2PTK_CUSTOM,
};
enum WINDOW_COORD_TYPE
{
	INVALID_TYPE = -1,
	EXIST_TYPE,
	REDRAW_TYPE,
};

enum DIRECTION_POSITION
{
	POS_TOP = 0,
	POS_BOTTOM,
	POS_RIGHT,
	POS_LEFT,
};

enum MORPHOLOGY_DIRECTION_TYPE
{
	DIRECTION_6C = 0,
	DIRECTION_LEFT,
	DIRECTION_RIGHT,
	DIRECTION_POSTERIOR,
	DIRECTION_ANTERIOR,
	DIRECTION_SUPERIOR,
	DIRECTION_INFERIOR,

};

enum AI_TYPE
{
	AI_LIVER = 0,
	AI_COUNT,
};

enum IMAGE_CALCULATOR_OPERATOR
{
	OP_PLUS = 0,
	OP_MINUS,
	OP_MULTIPLY,
	OP_DIVIDE,
	OP_REPLACE,
};

enum REGION_GROWING_MODE
{
	RG_MODE_HU_RANGE = 0,
	RG_MODE_LAYER
};

enum REGION_GROWING_CONNECTIVITY
{
	RG_CONNECTIVITY_26 = 0,
	RG_CONNECTIVITY_6
};

enum DRAW_CUT_SHAPE
{
	DRAW_CUT_SHAPE_NONE = 0,
	DRAW_CUT_SHAPE_CIRCULAR,
	DRAW_CUT_SHAPE_ANGULAR,
};

//typedef enum {
//	eLCETLastExecutedTime,	// last 접속 시간.(validation check 용도)
//	eLCETLoginIDSaveCheck,	// id save 플레그.
//	eLCETLoginID,			// id save시 저장할 ID.
//	eLCETLoginPWD,			// id save시 저장할 pwd.
//	eLCETLoginAuto,			// 자동 로그인 플레그.
//	eLCETLoginAutoID,		// 자동 로그인 아이디.
//	eLCETLoginAutoPWD,		// 자동 로그인 패스워드.
////	eLCETLicensedResult,	// 라이센스 성공/실패 플레그.
////	eLCETLicensedID,		// 라이센스 성공한 ID.
////	eLCETLicensedPWD,		// 라이센스 성공한 PWD.
//} eLicenseConfigElementType;
//
//typedef enum {
//	eLSPTLogin,
//	eLSPTChkLicence,
//	eLSPTGetVersion,
//	eLSPTChkFunctionUsableCount,
//	eLSPTDecreaseFunctionUsableCount,
//
//	// SSE control
//	eLSPTSSESubscribe,
//	eLSPTSSESubscribe_test,
//	eLSPTSSEUnSubscribe,
//	eLSPTSSEAddNotificationHistory,
//
//} eLicenseServerPathType;

/////////////////////////////////

enum DEEPCATCH_TYPE_PREDICT
{
	DTP_WHOLEBODY_ABDOMEN = 0,
	DTP_EXTRACT_VERTEBRA = 1,
	DTP_IO_LIVER_SPLEEN = 2,
	DTP_IO_AORTA = 3,
	DTP_CHEST = 4,
};

// deepcatch report UNET
enum eDeepcatchUNETType {
	eDUT2D,
	eDUT3D,
};

// deepcatch report Contrast
typedef enum {
	eDCTNoneContrast,
	eDCTContrast,
} eDeepcatchContrastType;

// deepcatch report Contrast
typedef enum {
	eDAWTCoronal,
	eDAWTSagittal,
} eDeepcatchAWSelectType;

//SUPPORT_DEEPCATCH_VERSION_2
// deepcatch report BodyType
typedef enum {
	eDCBTAbdomenWholeBody,
	eDCBTChest,
} eDeepcatchBodyType;

// deepcatch report VertebraType
typedef enum {
	eUseVertebraNetwork,
	eDCVTNone,
} eDeepcatchVertebraType;

// deepcatch report Contrast
typedef enum {
	eDCIO_Liver_Spleen,
	eDCIO_Aorta,
	eDCIO_Both,
	eDCIOTNone,
} eDeepcatchIONetworkType;

typedef enum {
	eSPCT_Low,
	eSPCT_Up,
	eSPCT_Mid
} eSlicePositionCalculateType;

typedef enum {
	eSST_MultiLow,
	eSST_MultiUp,
	eSST_Single	
} eSliceSelectionType;


typedef enum {
	eDCVB_T1,
	eDCVB_T2,
	eDCVB_T3,
	eDCVB_T4,
	eDCVB_T5,
	eDCVB_T6,
	eDCVB_T7,
	eDCVB_T8,
	eDCVB_T9,
	eDCVB_T10,
	eDCVB_T11,
	eDCVB_T12,
	eDCVB_L1,
	eDCVB_L2,
	eDCVB_L3,
	eDCVB_L4,
	eDCVB_L5,	
	eDCVB_MAX,
} eDeepcatchVertebraNumber;

typedef enum {
	eDCVB_Abdominal_waist = eDeepcatchVertebraNumber::eDCVB_MAX,
} eDeepcatchUINumAbdominal;


// deepcatch report Additional options
typedef enum {
	eDAONone,
	eDAOOnlyTrunk,
	eDAOQCT,
} eDeepcatchAdditionalOptions;

// deepcatch report ui gender input
typedef enum {
	eDGTUnknown,
	eDGTFemale,
	eDGTMale,
} eDeepcatchGenderType;

typedef enum {
	eDSliceSelectAuto,				// Auto
	eDSliceSelectUserDefine		// User Define
} eDeepcatchSliceSelectType;

// deepcatch report preferrence.
typedef enum {
	eDPTSingleSlice,
	eDPTMultiSlice,
	eDPTNone,
} eDeepcatchPreferenceType;

// application path, appdata path
typedef enum {
	eCFLApplicationPah,
	eCFLAppDataLocalPath,
} eConfigFileLocation;

// notice type
typedef enum {
	eNTServerRelocation,
	eNTNew,
} eNoticeType;

typedef enum {
	eNTCISubject,
//	eNTCIStartDate,
	eNTCIColumnMax
} eNoticeTreeColumnIndex;

typedef enum {
	eMACWRTSuccess,
	eMACWRTNextPredict,
	eMACWRTPredictCountErr,
} eMedipAICompleteWorkReturnType;

typedef enum {
	eMQMCAptTissue,
	eMQMCAbnormal1,
	eMQMCAbnormal2,
	eMQMCNormal,
	eMQMCMaxSize
} eMuscleQualityMapCategorization;

enum class eDeepPredictAICopyMask
{
	none_copy,
	copy,
};

enum class eAIContrastSynthesisOption
{
	Adult,
	Pediatric,
	NonContrast
};

enum class eOmniverseStatus
{
	Lock,
	Unlock
};

typedef struct {
	QString maskName;	// mask name
	QVector<QPair<QString, QString>> data;
} sLocalClinicalInfo;

struct sNoticeListInfo {
	long noticeSeq = -1;
	int noticeType = -1;
	QString noticeSubject = "";
	QString noticeContent = "";
	QString noticeStartDate = "";
	QString noticeEndDate = "";
};

typedef struct {
	int columnNum;
	QStringList data;
} sDeepcatchMacroColumnData;

typedef struct {
	int rowNum;
	QMap<QString, sDeepcatchMacroColumnData> rowMap;
} sDeepcatchMacroRowData;

typedef struct {
	int nFuncUsableCount;
	QString strFuncUsableCountState;
} sFuncUsableCountResult;

typedef struct {
	QString strSeriesDescription;
	muint32 nSelectedSeriesIndex;
	int nNumberOfImages;
} sSelectedSeriesInfo;

struct sReportOtherInfo {
	QString strSelectedSeriesDescription = "";
};

#define RT_NONE					0
#define RT_VOLUME				0x0001
#define RT_MASK					0x0010
#define RT_SURFACE				0x0100
#define RT_VOLUME_MASK			RT_VOLUME | RT_MASK
#define RT_VOLUME_SURFACE		RT_VOLUME | RT_SURFACE
#define RT_MASK_SURFACE			RT_MASK | RT_SURFACE
#define RT_VOLUME_MASK_SURFACE	RT_VOLUME | RT_MASK | RT_SURFACE

#define RT_SHOW					0x01
#define RT_SELECT				0x10

// action cache 파일시 ID로 사용
#define ACT_ID_MARKING											1000000001
#define ACT_ID_UNMARKING										1100000001
#define ACT_ID_UNMARKING2										1200000001
#define ACT_ID_POLYFILL											1300000001
#define ACT_ID_POLYFILL3D										1310000001
#define ACT_ID_DRAWFILL											1400000001
#define ACT_ID_DRAWFILL3D										1410000001
#define ACT_ID_SPLIT3D											1420000001
#define ACT_ID_DRAWSEED											1500000001
#define ACT_ID_OVALFILL											1600000001

#define ACT_ID_BOUNDINGBOX_M									1900000001

#define ACT_ID_MASKLIST_ADD										201000001
#define ACT_ID_MASKLIST_ADD_MEDFILE								201100001
#define ACT_ID_MASKLIST_ADD_RAWFILE								201200001
#define ACT_ID_MASKLIST_CLEAR_ONE								201300001
#define ACT_ID_MASKLIST_ADD_ROIFILE								201400001
#define ACT_ID_MASKLIST_ADD_TXTFILE								201500001
#define ACT_ID_MASKLIST_ADD_NIIFILE								201600001

#define ACT_ID_MASKLIST_SPLIT_REGION							201700001
#define ACT_ID_MASKLIST_IMAGE_CALCULATE							201800001

#define ACT_ID_MASKLIST_COPY									202000001
#define ACT_ID_MASKLIST_DEL										203000001
#define ACT_ID_MASKLIST_COLOR									204000001
#define ACT_ID_MASKLIST_INVERT									205000001
#define ACT_ID_MASKLIST_INTERSECT								206000001 //차집합
#define ACT_ID_MASKLIST_MOVE									207000001
#define ACT_ID_MASKLIST_MERGE									208000001
#define ACT_ID_MASKLIST_TEXT_CHANGE								209000001
#define ACT_ID_MASKLIST_ZFLIP									210000001
#define ACT_ID_MASKLIST_YFLIP									220000001
#define ACT_ID_MASKLIST_XFLIP									230000001
#define ACT_ID_MASKLIST_DELS									240000001
#define ACT_ID_MASKLIST_INTERSECTION							250000001 //교집합
#define	ACT_ID_SEED_COLOR										260000001
#define	ACT_ID_SEED_CLEAR										270000001
#define ACT_ID_SEED_ADD											280000001
#define ACT_ID_SEED_DEL											290000001

#define ACT_ID_DD_PREDICT										300000001
#define ACT_ID_DD_OUTSET										310000001

#define ACT_ID_TRANS_PREDICT									320000001
#define ACT_ID_CONTRAST_SYNTHESIS								320000002

#define ACT_ID_KERNEL_CONTINOUS_CONVERSION						330000001
#define ACT_ID_KERNEL_NEUTRALIZATION_CONVERSION					340000001
#define ACT_ID_LOWDOSE_RECONSTRUCTION							350000001

#define ACT_ID_MESHLIST_ADD										501000001
#define	ACT_ID_MESHLIST_DEL										502000001
#define ACT_ID_MESHLIST_DEL_LIST								503000001
#define ACT_ID_MESHLIST_UPDATE									504000001
#define ACT_ID_MESHLIST_SPLIT									505000001
#define ACT_ID_MESHLIST_COLOR_CHANGE							506000001
#define ACT_ID_MESHLIST_NAME_CHANGE								507000001
#define ACT_ID_MESHLIST_UID_CHANGE								508000001
#define ACT_ID_MESHLIST_SCALE_CHANGE							509000001
#define ACT_ID_MESHLIST_TRANS_CHANGE							510000001
#define ACT_ID_MESHLIST_ALIGN_UPDATE							511000001
#define ACT_ID_MESHLIST_ROT_CHANGE								512000001

#define ACT_ID_MESHLIST_CREATE_MESH								520000001

#define ACT_ID_REGIONGROWING									3000000001
#define ACT_ID_REGIONALLSEL										3010000001
#define ACT_ID_IMAGE_EROSION									3100000001
#define ACT_ID_IMAGE_DILATION									3200000001
#define ACT_ID_IMAGE_ENHANCE									3300000001
#define ACT_ID_IMAGE_ENHANCE_ORIGIN								3390000001
#define ACT_ID_IMAGE_GAUSSIAN									3380000001
#define ACT_ID_IMAGE_LAPLACIAN									3370000001
#define ACT_ID_IMAGE_DRAWCUT									3400000001
#define ACT_ID_IMAGE_BOUNDARY									3500000001
#define ACT_ID_IMAGE_HOLEFILLING								3600000001
#define ACT_ID_IMAGE_VESSELNESS									3700000001
#define ACT_ID_IMAGE_FISSURENESS								3800000001
#define ACT_ID_IMAGE_FEATUREEXTRACTOR_ADD						3900000001
#define ACT_ID_IMAGE_FEATUREEXTRACTOR_DEL						3910000001
#define ACT_ID_IMAGE_SUBFEATUREEXTRACTOR_ADD					3920000001
#define ACT_ID_IMAGE_SUBFEATUREEXTRACTOR_DEL					3930000001
#define ACT_ID_IMAGE_ISOTROPIC									4000000001
#define ACT_ID_IMAGE_ISOTROPIC_MODIFICATION				4010000001
#define ACT_ID_IMAGE_LEVEL_SET									4100000001
#define ACT_ID_IMAGE_SCALE										4200000001
#define ACT_ID_IMAGE_MOVE										4300000001

// 이 밑부터 int 형 overflow, bug 가능성 있음
#define ACT_ID_IMAGE_CROP										4400000001
#define ACT_ID_ANNO_TEXT_ADD									5110000001
#define ACT_ID_ANNO_DEL											5120000001
#define ACT_ID_ANNO_TEXT_MOVE									5130000001
#define ACT_ID_ANNO_TEXT_EDIT									5140000001
#define ACT_ID_ANNO_LEN_ADD										5150000001
#define ACT_ID_ANNO_LEN_MOVE									5160000001
#define ACT_ID_ANNO_LEN_EDIT									5170000001
#define ACT_ID_ANNO_ANGLE_ADD									5180000001
#define ACT_ID_ANNO_ANGLE_MOVE									5190000001
#define ACT_ID_ANNO_ANGLE_EDIT									5200000001
#define ACT_ID_ANNO_OVAL_ADD									5210000001
#define ACT_ID_ANNO_OVAL_MOVE									5220000001
#define ACT_ID_ANNO_OVAL_EDIT									5230000001
#define ACT_ID_ANNO_ARROW_ADD									5240000001
#define ACT_ID_ANNO_ARROW_MOVE									5250000001
#define ACT_ID_ANNO_ARROW_EDIT									5260000001
#define	ACT_ID_ANNO_PATH_ADD									5270000001
#define ACT_ID_ANNO_PATH_DEL									5280000001
#define	ACT_ID_ANNO_PATH_CLEAR									5290000001
#define ACT_ID_ANNO_PATH_TAB_ADD								5300000001
#define ACT_ID_ANNO_RECTANGLE_ADD								5310000001
#define ACT_ID_ANNO_RECTANGLE_MOVE								5320000001
#define ACT_ID_ANNO_RECTANGLE_EDIT								5330000001


#define ACT_ID_PROFILE_DEL										6000000001
#define ACT_ID_PROFILE_COL_CHANGE								6100000001
#define ACT_ID_INTER_SELECTION									6200000001
#define	ACT_IP_INTER_RECT_SELECTION								6300000001

#define ACT_ID_MASKLIST_MESH_CONNECT							6400000001
#define ACT_ID_MASKLIST_MESHES_CONNECT							6500000001

#define ACT_ID_CAPTURE_ADD										7000000001
#define ACT_ID_CAPTURE_DEL										7100000001

#define ACT_ID_IMAGE_DEL										8000000001
#define ACT_ID_IMAGE_IMPORT										8100000001

#define ACT_ID_CUDA_LIVER_ADD									9000000001

typedef void(*progUpdatefunc)(int value, void * data);
typedef bool(*progCheckfunc)();

typedef std::vector<unsigned char> AIClassResult;
typedef std::vector<AIClassResult> AIClassResultList;
typedef std::vector<std::string> AIClassNameList;

