#pragma once
#include "graphics/color.h"
#include "defineMEDIP.h"

#include <QIcon>
#include <qcolor.h>
#include <QFont>
#include <qmap.h>

class QImage;
class QByteArray;

enum RICON
{
	ICON_FILE_OPEN = 0,
	ICON_FILE_NON_OPEN,
	ICON_FILE_OPEN_HOVER,

	ICON_FILE_OPEN_FILEMANAGER,
	ICON_FILE_NON_OPEN_FILEMANAGER,
	ICON_FILE_OPEN_FILEMANAGER_HOVER,

	ICON_CROP_OPEN,
	ICON_CROP_NON_OPEN,
	ICON_CROP_OPEN_HOVER,

	ICON_FILE_SAVE,
	ICON_FILE_NON_SAVE,
	ICON_FILE_SAVE_HOVER,

	ICON_FILE_SAVE_AS,
	ICON_FILE_NON_SAVE_AS,
	ICON_FILE_SAVE_AS_HOVER,

	ICON_FILE_UPLOAD,
	ICON_FILE_NON_UPLOAD,
	ICON_FILE_UPLOAD_HOVER,

	ICON_PACS_UPLOAD,
	ICON_PACS_NON_UPLOAD,
	ICON_PACS_UPLOAD_HOVER,

	ICON_UNDO,
	ICON_UNDO_PRESS,
	ICON_NON_UNDO,
	ICON_UNDO_HOVER,

	ICON_REDO,
	ICON_REDO_PRESS,
	ICON_NON_REDO,
	ICON_REDO_HOVER,

	ICON_ANIMATION_SINGLE,
	ICON_ANIMATION_SINGLE_HOVER,
	ICON_ANIMATION_SINGLE_PRESS,
	ICON_ANIMATION_PLAY_AB,
	ICON_ANIMATION_PLAY_AB_HOVER,
	ICON_ANIMATION_PLAY_AB_PRESS,
	ICON_ANIMATION_PLAY_BA,
	ICON_ANIMATION_PLAY_BA_HOVER,
	ICON_ANIMATION_PLAY_BA_PRESS,

	ICON_RESET,
	ICON_NON_RESET,
	ICON_RESET_HOVER,

	ICON_CLEAR,

	ICON_INACT,
	ICON_NON_INACT,
	ICON_INACT_HOVER,

	ICON_APP,
	ICON_LIST_VISIBLE,
	ICON_LIST_INVISIBLE,
	ICON_LIST_LOCKER_OPEN,
	ICON_LIST_LOCKER_CLOSE,
	ICON_LIST_MESH_VISIBLE,

	ICON_NON_MIX,
	ICON_MIX,
	ICON_MIX_HOVER,

	ICON_NON_TAB,
	ICON_TAB,
	ICON_TAB_HOVER,

	ICON_NON_2D_VIEW_ON_3D,
	ICON_2D_VIEW_ON_3D,
	ICON_2D_VIEW_ON_3D_HOVER,

	ICON_NON_PLANE_CUT,
	ICON_PLANE_CUT,
	ICON_PLANE_CUT_HOVER,

	ICON_NON_FILL_HOLE,
	ICON_FILL_HOLE,
	ICON_FILL_HOLE_HOVER,
	
	// Mesh Edit
	ICON_NON_BRUSH_SCULPT,
	ICON_BRUSH_SCULPT,
	ICON_BRUSH_SCULPT_HOVER,

	ICON_NON_BRUSH_OP_SURFACE,
	ICON_BRUSH_OP_SURFACE,
	ICON_BRUSH_OP_SURFACE_HOVER,

	ICON_NON_BRUSH_OP_VOLUME,
	ICON_BRUSH_OP_VOLUME,
	ICON_BRUSH_OP_VOLUME_HOVER,

	ICON_NON_SCULPT_OP_SMOOTH,
	ICON_SCULPT_OP_SMOOTH,
	ICON_SCULPT_OP_SMOOTH_HOVER,

	ICON_NON_SCULPT_OP_INFLATE,
	ICON_SCULPT_OP_INFLATE,
	ICON_SCULPT_OP_INFLATE_HOVER,

	ICON_NON_SCULPT_OP_DEFLATE,
	ICON_SCULPT_OP_DEFLATE,
	ICON_SCULPT_OP_DEFLATE_HOVER,

	ICON_NON_SCULPT_OP_REDUCE,
	ICON_SCULPT_OP_REDUCE,
	ICON_SCULPT_OP_REDUCE_HOVER,

	ICON_NON_SCULPT_OP_REFINE,
	ICON_SCULPT_OP_REFINE,
	ICON_SCULPT_OP_REFINE_HOVER,

	ICON_NON_SCULPT_OP_MOVE,
	ICON_SCULPT_OP_MOVE,
	ICON_SCULPT_OP_MOVE_HOVER,

	ICON_NON_SCULPT_OP_DRAG,
	ICON_SCULPT_OP_DRAG,
	ICON_SCULPT_OP_DRAG_HOVER,

	ICON_NON_BRUSH_SELECT,
	ICON_BRUSH_SELECT,
	ICON_BRUSH_SELECT_HOVER,

	ICON_NON_MESH_OBJECTS,
	ICON_MESH_OBJECTS,
	ICON_MESH_OBJECTS_HOVER,

	ICON_NON_SCULPT_OP_HOLEFILL,
	ICON_SCULPT_OP_HOLEFILL,
	ICON_SCULPT_OP_HOLEFILL_HOVER,

	ICON_NON_ALPHA_IMG,
	ICON_ALPHA_IMG,
	ICON_ALPHA_IMG_HOVER,

	ICON_ANNO_LENGTH,
	ICON_NON_ANNO_LENGTH,
	ICON_ANNO_LENGTH_HOVER,

	ICON_ANNO_ARROW,
	ICON_NON_ANNO_ARROW,
	ICON_ANNO_ARROW_HOVER,

	ICON_ANNO_RECT,
	ICON_NON_ANNO_RECT,
	ICON_ANNO_RECT_HOVER,

	ICON_VIEW_OVALROI,
	ICON_VIEW_NON_OVALROI,
	ICON_VIEW_OVALROI_HOVER,

	ICON_ANNO_ANGLE,
	ICON_NON_ANNO_ANGLE,
	ICON_ANNO_ANGLE_HOVER,

	ICON_ANNO_PROF_LINE,
	ICON_NON_ANNO_PROF_LINE,
	ICON_ANNO_PROF_LINE_HOVER,

	ICON_VIEW_POLYROI,
	ICON_VIEW_NON_POLYROI,
	ICON_VIEW_POLYROI_HOVER,

	ICON_VIEW_POLYFREE,
	ICON_VIEW_NON_POLYFREE,
	ICON_VIEW_POLYFREE_HOVER,

	ICON_VIEW_FREEDRAWROI,
	ICON_VIEW_NON_FREEDRAWROI,
	ICON_VIEW_FREEDRAWROI_HOVER,

	ICON_VIEW_PICKERROI,
	ICON_VIEW_NON_PICKERROI,
	ICON_VIEW_PICKERROI_HOVER,

	ICON_VIEW_NON_SKETCHDRAWSEGMENTATION_OK,
	ICON_VIEW_SKETCHDRAWSEGMENTATION_OK,
	ICON_VIEW_NON_SKETCHDRAWSEGMENTATION,
	ICON_VIEW_SKETCHDRAWSEGMENTATION_HOVER,
	ICON_VIEW_SKETCHDRAWSEGMENTATION_OK_HOVER,

	ICON_VIEW_ANGLEDROI,
	ICON_VIEW_NON_ANGLEDROI,
	ICON_VIEW_ANGLEDROI_HOVER,

	ICON_VIEW_FULL_SCREEN,
	ICON_VIEW_NON_FULL_SCREEN,
	ICON_VIEW_FULL_SCREEN_HOVER,

	ICON_VIEW_COORD,
	ICON_VIEW_NON_COORD,
	ICON_VIEW_COORD_HOVER,

	ICON_VIEW_2D_AXISES,
	ICON_VIEW_NON_2D_AXISES,
	ICON_VIEW_2D_AXISES_HOVER,

	ICON_VIEW_FIT_COORD,
	ICON_VIEW_NON_FIT_COORD,
	ICON_VIEW_FIT_COORD_HOVER,

	///////////////
	ICON_DEEPCATCH_VIEW_L3,
	ICON_DEEPCATCH_VIEW_NON_L3,
	ICON_DEEPCATCH_VIEW_L3_HOVER,


	ICON_DEEPCATCH_VIEW_AW,
	ICON_DEEPCATCH_VIEW_NON_AW,
	ICON_DEEPCATCH_VIEW_AW_HOVER,
	//////////////


	ICON_VIEW_NON_BOUNDARY, /*non Boundary press*/
	ICON_VIEW_NON_BOUNARY_HOVER, /*boundary 상태에서 mouse hover*/
	ICON_VIEW_BOUNARY, /*boundary press*/
	ICON_VIEW_BOUNARY_HOVER, /*non boundary 상태에서 mouse hover*/


	ICON_ROILIST_NEW,
	ICON_ROILIST_NON_NEW,
	ICON_ROILIST_NEW_HOVER,


	ICON_ROILIST_COPY,
	ICON_ROILIST_NON_COPY,
	ICON_ROILIST_COPY_HOVER,

	ICON_ROILIST_DEL,
	ICON_ROILIST_NON_DEL,
	ICON_ROILIST_DEL_HOVER,

	ICON_ANNO_TEXT,
	ICON_NON_ANNO_TEXT,
	ICON_ANNO_TEXT_HOVER,

	ICON_APP_INFO,
	ICON_NON_APP_INFO,
	ICON_APP_INFO_HOVER,

	ICON_UPDATE_MASK,
	ICON_NON_UPDATE_MASK,
	ICON_UPDATE_MASK_HOVER,

	ICON_HISTOGRAM,
	ICON_NON_HISTOGRAM,
	ICON_HISTOGRAM_HOVER,

	ICON_LINK,
	ICON_NON_LINK,
	ICON_LINK_HOVER,

	ICON_ANNO_PATH,
	ICON_NON_ANNO_PATH,
	ICON_ANNO_PATH_HOVER,

	ICON_ANNO_PATH_PLAY,
	ICON_NON_ANNO_PATH_PLAY,
	ICON_ANNO_PATH_PLAY_HOVER,

	ICON_NON_STOP,
	ICON_STOP,
	ICON_STOP_HOVER,

	ICON_ROILIST_MERGE,
	ICON_ROILIST_NON_MERGE,
	ICON_ROILIST_MERGE_HOVER,

	ICON_ROILIST_FFS,
	ICON_ROILIST_NON_FFS,
	ICON_ROILIST_FFS_HOVER,

	ICON_SVIEW,
	ICON_SVIEW_HOVER,
	ICON_NON_SVIEW,

	ICON_REPORT_NEW_FORMAT,
	ICON_REPORT_NEW_FORMAT_HOVER,
	ICON_NON_REPORT_NEW_FORMAT,

	ICON_REPORT_SAVE_FORMAT,
	ICON_REPORT_SAVE_FORMAT_HOVER,
	ICON_NON_REPORT_SAVE_FORMAT,

	ICON_REPORT_SAVE_AS_FORMAT,
	ICON_REPORT_SAVE_AS_FORMAT_HOVER,
	ICON_NON_REPORT_SAVE_AS_FORMAT,

	ICON_REPORT_DELETE_FORMAT,
	ICON_REPORT_DELETE_FORMAT_HOVER,
	ICON_NON_REPORT_DELETE_FORMAT,

	ICON_REPORT_TEXT_COLOR,
	ICON_REPORT_TEXT_COLOR_HOVER,
	ICON_NON_REPORT_TEXT_COLOR,

	ICON_REPORT_TEXT_BOLD,
	ICON_REPORT_TEXT_BOLD_HOVER,
	ICON_NON_REPORT_TEXT_BOLD,

	ICON_REPORT_TEXT_ITALIC,
	ICON_REPORT_TEXT_ITALIC_HOVER,
	ICON_NON_REPORT_TEXT_ITALIC,

	ICON_REPORT_TEXT_UNDER_LINE,
	ICON_REPORT_TEXT_UNDER_LINE_HOVER,
	ICON_NON_REPORT_TEXT_UNDER_LINE,

	ICON_REPORT_TEXT_LEFT_ALIGN,
	ICON_REPORT_TEXT_LEFT_ALIGN_HOVER,
	ICON_NON_REPORT_TEXT_LEFT_ALIGN,

	ICON_REPORT_TEXT_CENTER_ALIGN,
	ICON_REPORT_TEXT_CENTER_ALIGN_HOVER,
	ICON_NON_REPORT_TEXT_CENTER_ALIGN,

	ICON_REPORT_TEXT_RIGHT_ALIGN,
	ICON_REPORT_TEXT_RIGHT_ALIGN_HOVER,
	ICON_NON_REPORT_TEXT_RIGHT_ALIGN,

	ICON_REPORT_TEXT_JUSTIFY_ALIGN,
	ICON_REPORT_TEXT_JUSTIFY_ALIGN_HOVER,
	ICON_NON_REPORT_TEXT_JUSTIFY_ALIGN,

	ICON_REPORT_TEXT_HEADER_LIST,
	ICON_REPORT_TEXT_HEADER_LIST_HOVER,
	ICON_NON_REPORT_TEXT_HEADER_LIST,

	ICON_REPORT_TEXT_HEADER_SQUARE,

	ICON_REPORT_TEXT_HEADER_DISC,

	ICON_REPORT_TEXT_HEADER_CIRCLE,

	ICON_REPORT_TEXT_SEQUENCE_LIST,
	ICON_REPORT_TEXT_SEQUENCE_LIST_HOVER,
	ICON_NON_REPORT_TEXT_SEQUENCE_LIST,

	ICON_REPORT_TEXT_SEQUENCE_DECIMAL,

	ICON_REPORT_TEXT_SEQUENCE_LOWER_ALPHA,

	ICON_REPORT_TEXT_SEQUENCE_UPPER_ALPHA,

	ICON_REPORT_TEXT_SEQUENCE_LOWER_ROMAN,

	ICON_REPORT_TEXT_SEQUENCE_UPPER_ROMAN,

	ICON_REPORT_CREATE_TABLE,
	ICON_REPORT_CREATE_TABLE_HOVER,
	ICON_NON_REPORT_CREATE_TABLE,

	ICON_REPORT_MERGE_CELL,
	ICON_REPORT_MERGE_CELL_HOVER,
	ICON_NON_REPORT_MERGE_CELL,

	ICON_REPORT_SPLIT_CELL,
	ICON_REPORT_SPLIT_CELL_HOVER,
	ICON_NON_REPORT_SPLIT_CELL,

	ICON_REPORT_INSERT_ROW,
	ICON_REPORT_INSERT_ROW_HOVER,
	ICON_NON_REPORT_INSERT_ROW,

	ICON_REPORT_INSERT_COLUMN,
	ICON_REPORT_INSERT_COLUMN_HOVER,
	ICON_NON_REPORT_INSERT_COLUMN,

	ICON_REPORT_CELL_PROPERTY,
	ICON_REPORT_CELL_PROPERTY_HOVER,
	ICON_NON_REPORT_CELL_PROPERTY,

	ICON_REPORT_IMPORT,
	ICON_REPORT_IMPORT_HOVER,
	ICON_NON_REPORT_IMPORT,

	ICON_REPORT_EXPORT,
	ICON_REPORT_EXPORT_HOVER,
	ICON_NON_REPORT_EXPORT,

	ICON_REPORT_PRINT,
	ICON_REPORT_PRINT_HOVER,
	ICON_NON_REPORT_PRINT,

	ICON_IMAGE_MANAGEMENT_TAB,
	ICON_IMAGE_MANAGEMENT_TAB_HOVER,
	ICON_NON_IMAGE_MANAGEMENT_TAB,

	ICON_NON_SPLIT_CURVE,
	ICON_SPLIT_CURVE,
	ICON_SPLIT_CURVE_HOVER,

	ICON_NON_3D_ANGLE_SPLIT,
	ICON_3D_ANGLE_SPLIT_DOWN,
	ICON_3D_ANGLE_SPLIT_HOVER,

	ICON_NON_MESH_ZERO,
	ICON_MESH_ZERO,
	ICON_MESH_ZERO_HOVER,

	ICON_NON_MESH_CUBE,
	ICON_MESH_CUBE,
	ICON_MESH_CUBE_HOVER,

	ICON_NON_MESH_SPHERE,
	ICON_MESH_SPHERE,
	ICON_MESH_SPHERE_HOVER,

	ICON_NON_MESH_CYLINDER,
	ICON_MESH_CYLINDER,
	ICON_MESH_CYLINDER_HOVER,

	ICON_NON_DIFF,
	ICON_DIFF,
	ICON_DIFF_HOVER,

	ICON_NON_UNION,
	ICON_UNION,
	ICON_UNION_HOVER,

	ICON_NON_INTERSECT,
	ICON_INTERSECT,
	ICON_INTERSECT_HOVER,

	ICON_NON_RADIOMICS_HEIGHTMAP,	
	ICON_RADIOMICS_HEIGHTMAP,
	ICON_RADIOMICS_HEIGHTMAP_HOVER,

	ICON_STATUS_BAR_GRAB_RESIZE
};


enum RIMAGE
{
	IMG_UNLOAD = 0,
};

class ResourceManager
{
public:
	static ResourceManager * getSingleton();
	ResourceManager();
	~ResourceManager();

	bool init();
	void clear();

	QIcon			getIcon(RICON icon_type, int width = 0, int height = 0);
	QImage *		getUnloadImage(WINDOW_TYPE type);
	QImage *		getDirectionImage(WINDOW_TYPE type = WT_AXIAL, int position = POS_TOP);
	QImage *		getWaterMark();
	QImage *		getTexture_CullingPlane() { return image3DCullingPlane; }
	QColor			getUnloadBackGroundColor() { return unloadBackGroundColor; }
	QImage *		getTexture_Font() { return image3DFontNotoSansRegular; }

	QIcon GetIcon_ListVisible(bool visible);
	QIcon GetIcon_ListOmniverseLock(eOmniverseStatus status);

	QFont			fontNormal;
	QMap<QString, QByteArray*> imageMap;

private:
	QImage *		imageUnloadAxial;
	QImage *		imageUnloadCoronal;
	QImage *		imageUnloadSagittal;
	QImage *		imageUnloadSubView;
	QImage *		imageUnloadVolume;
	QImage *		imageWaterMark;

	QImage *		image3DCullingPlane;
	QImage *		image3DFontNotoSansRegular;

	QImage *		imageRight;
	QImage *		imageLeft;
	QImage *		imageAnterior;
	QImage *		imagePosterior;
	QImage *		imageAnteriorHori;
	QImage *		imagePosteriorHori;
	QImage *		imageSuperior;
	QImage *		imageInferior;

	QColor			unloadBackGroundColor;
};

#define RESOURCE_MANAGER ResourceManager::getSingleton()