#pragma once

#ifndef STRING_MANAGER_H
#define STRING_MANAGER_H

#include "define.h"
#include <QString>
#include <qmap.h>
#include <qobject.h>

class QImage;

enum RSTRING
{
	STR_OPEN = 0,
	STR_MEDIP_FILE_SAVE,
	STR_MEDIP_FILE_OPEN,
	STR_CROP,
	//	STR_SAVE, //STR_SAVE_FILE
	STR_SAVE_AS,
	STR_UPLOAD_PACS,
	STR_UNDO,
	STR_REDO,
	STR_LOAD,
	STR_UPLOAD,
	STR_UPLOAD_SUCCESS,
	STR_UPLOAD_FAIL,

	STR_REMOTE_FILE,
	STR_REMOTE_FILE_DELAYED,

	STR_FILE_TRANSFER,
	STR_TRANSFER_DESC,

	STR_SAVE_FILE,
	STR_SAVE_FILE_DESC,

	STR_CONTACT,
	STR_SEGMENT,
	STR_MEASUREMENT,
	STR_MESH_EDITING,
	STR_REPORT,
	STR_PLANNING,
	STR_TA,

	STR_ENHANCED,
	STR_ROI,
	STR_INFO,
	STR_WINDOW_WL,
	STR_DEFAULT,
	STR_RECOMMEND_1,
	STR_RECOMMEND_2,
	STR_BONE,
	STR_LUNG,
	STR_MEDIASTINAL,
	STR_BRAIN,
	STR_ABD,
	STR_LIVER,
	STR_KIDNEY,
	STR_URINARY_TRACK_BLADDER,
	STR_CUSTOM,
	STR_WIDTH,
	STR_HEIGHT,
	STR_LEVEL,
	STR_GAMMA,
	STR_WORK,
	STR_OK,
	STR_CANCEL,
	STR_AUTO,
	STR_RESET,
	STR_APPLY,

	STR_SOFT_TISSUE,
	STR_AIR,
	STR_FAT,
	STR_FLUIDS,


	STR_Z_FLIP,
	STR_LEVEL_SET,
	STR_PASSWORD,
	STR_IMG_ENHANCED,
	STR_IMG_CIRCUMFERENCE,
	STR_ORG_IMG,
	STR_RG,
	STR_NOT_SELECTED,
	STR_SELECT_SEED,
	STR_IRP,
	STR_SEED_APPLY,
	STR_ALL_SELECT,
	STR_RG_ALL,
	STR_ISOTROPIC,
	STR_DRAW_CUT,

	STR_ROI_LIST,
	STR_CLR_ROI,
	STR_NEW,
	STR_RENAME,
	STR_DELETE,
	STR_COPY,
	STR_INVERSE,
	STR_FFS_ROI,
	STR_INTERSECTION_ROI,
	STR_MERGE,
	STR_SPLIT_REGION,
	STR_EROSION_ROI,
	STR_DILATION_ROI,
	STR_MOVE_MASK_ROI,
	STR_SET_SEED_POINT,
	STR_HOLEFILLING_ROI,
	STR_HOLEFILLING2D_ROI,
	STR_COMPONENT_ROI,
	STR_VESSELNESS_ROI,
	STR_FISSURENESS_ROI,
	STR_ANTI_MULTIPLE,
	STR_SELECT_2_WARN,
	STR_SELECT_MORE,
	STR_SELECT_SEED_FIRST,
	STR_SELECT_RANGE_FIRST,
	STR_SELECT_L3,
	STR_SELECT_ABDOMINAL_WAIST,
	STR_WARN,
	STR_SCALE_NOT_MATCHED,
	STR_3D_INTERPOLATION,

	STR_SERIES_DESC,

	STR_INVALID_NUMBER,
	STR_LOAD_FIRST,
	STR_LOAD_DICOM_FILE,
	STR_CROPPING_DICOM_DATA,
	STR_LOAD_DICOM_FILE_FAIL,
	STR_LOAD_FILE,
	STR_DELETE_FIRST,
	STR_DIFFER_SIZE,

	STR_IMG_EROSION,
	STR_IMG_DILATION,
	STR_IMG_MOVE,
	STR_IMG_COMPONENT_CHOISE,
	STR_EXPORT_STL,
	STR_EXPORT_OBJ,
	STR_EXPORT_RAW,
	STR_EXPORT_HURAW,
	STR_EXPORT_VTK,
	STR_EXPORT_NII,
	STR_EXPORT_NRRD,
	STR_EXPORT_TXT,
	STR_EXPORT_SPLIT_FILE,
	STR_EXPORT_3MF, 
	STR_EXPORT_USD, 

	STR_SAVE_CAPTURE,

	STR_EXIST_TEMP_FILE,


	STR_FORWARD_SEED,
	STR_BACKWARD_SEED,
	STR_X_FLIP,
	STR_Y_FLIP,

	STR_FAILED_TO,

	STR_MODALITY,
	STR_MACHINE_MODEL,
	STR_STUDY_DESC,
	STR_ID,
	STR_UID,
	STR_IMG_POS,
	STR_IMG_ORIENTATION,
	STR_EXAM_DATE,
	STR_NAME,
	STR_SLICE,
	STR_ACQUISITION_TIME,
	STR_SLICE_THICK,
	STR_SEX,
	STR_KVP,
	STR_AGE,
	STR_WEIGHT,
	STR_MAS,
	STR_WXH,
	STR_X_SPACING,
	STR_Y_SPACING,
	STR_Z_SPACING,
	STR_KERNEL,
	STR_MANUFACTURER,
	STR_MANUFACTURER_MODEL,
	STR_STUDY_INSTANCE_UID,
	STR_SERIES_INSTANCE_UID,
	STR_EXAM_ID,
	STR_ACCESSION_NUMBER,
	STR_ECHO_TIME,
	STR_REPETITION_TIME,
	STR_MAGNETIC_FIELD_STRENGTH,
	STR_FILP_ANGLE,

	STR_NONE_DEEPDRAW_PACK,


	STR_SMOOTHING_LEVEL,
	STR_PREVIEW_SURFACE,
	STR_SAVE_OBJ_FILE,
	STR_SAVE_TXT_FILE,

	STR_COLOR_CHANGE,
	STR_TEXT_SIZE,
	STR_ONE_SELECT,

	STR_HISTOGRAM_DESC,

	STR_INIT_FAIL,
	//STR_DX_INIT_FAIL,
	STR_APP_INIT_FAIL,
	STR_APP_LICENSE_FAIL,
	STR_APP_PASSWORD_FAIL,
	//STR_RC_INIT_FAIL,
	STR_APP_SYSTEMDATE_INVALID,
	//STR_APP_MEDIPVERSIONINFO_FILE_LOAD_FAIL,

	STR_INFO_DESC,


	STR_INFO_DIALOG,
	STR_LOGIN_DIALOG,
	STR_OFFLINELICENSEREG_DIALOG,

	STR_COPY_CODE,
	STR_ACTIVATE,

	STR_PROGRAM_VERSION,
	STR_PROGRAM_EDITION,	//
	STR_PROGRAM_COPYRIGHT,
	STR_MEDICALIP_ADDR,
	STR_OPENSOURCE,
	STR_MODULE_INFO,
	STR_PROGRAM_DESC,		//
	STR_LICENSE_WARN,
	STR_PROGRAM_TITLE_CONTENT,//
	STR_PASSED_MSG,

	//STR_ALREADY_EXECUTE,	
	STR_WORK_THREAD,
	STR_WORK_THREAD_CANCEL,
	STR_WORK_THREAD_FAIL,

	STR_SEED_POINT,
	STR_SEED_POINT_SHOW,
	STR_SEED_POINT_HIDE,
	STR_ANNO_LIST,
	STR_ANNO_TEXT,
	STR_ANNO_LENGTH,
	STR_ANNO_ANGLE,
	STR_ANNO_OVAL,
	STR_ANNO_ARROW,
	STR_ANNO_RECTANGLE,
	STR_ANNO_PROF_DRAW,
	STR_ANNO_PROF_POLY,

	STR_2D_SCREEN,
	STR_3D_VOLUME,

	STR_MIX,
	STR_LAYER_HISTOGRAM,

	STR_SHOW_ANI_POINT,
	STR_HIDE_ANI_POINT,

	STR_SHOW_ANNO,
	STR_HIDE_ANNO,

	STR_VR_POINT,
	STR_3D_TO_2D,

	STR_SVIEW,

	STR_ANNOTATION,
	STR_PRESET,
	//STR_ALLOC_FAIL,

	STR_MEDIPWINDOW_TITLE,
	STR_CONNECT_HOMEPAGE,
	STR_TABLIST_BTN_TOOLTIP,
	STR_IMAGELIST_BTN_TOOLTIP,

	STR_MESSAGE_FILE_LOAD_FAILED,

	STR_MESSAGE_TITLE_CROPOPEN_FILE_FAILED,
	STR_MESSAGE_TEXT_CROPOPEN_FILE_FAILED,

	STR_CROP_WINDOW_TILE,
	STR_CROP_MEMORY_INFO,
	STR_CROP_LENGTH_INFO,
	STR_CROP_DEPTH_INFO,
	STR_COUNT,

	STR_CAPTURE_TAB,
	STR_IMAGE_IMPORT_TAB,

	STR_BTN_TA_FEATURE_ALL_EXTRACT,
	STR_BTN_TA_FEATURE_EXTRACT,

	// Radiomics feature name

	// 대분류:MAJOR, 중분류: MIDDLE, 소분류: MINOR
	// MAJOR
	STR_TA_MAJOR_SIZE_AND_SHAPE_BASED_FEATURES,
	STR_TA_MAJOR_HISTOGRAM_BASED_FEATURES,
	STR_TA_MAJOR_RELATIONSHIPS_BETWEEN_IMAGE_VOXELS_BASED_FEATURES,

	// MIDDLE	
	STR_TA_MIDDLE_FIRST_ORDER_STATISTICS,
	STR_TA_MIDDLE_SHAPE_BASED_3D,
	STR_TA_MIDDLE_SHAPE_BASED_2D,
	STR_TA_MIDDLE_GRAY_LEVEL_COOCCURRENCE_MATRIX,
	STR_TA_MIDDLE_GRAY_LEVEL_RUN_LENGTH_MATRIX,
	STR_TA_MIDDLE_GRAY_LEVEL_SIZE_ZONE_MATRIX,
	STR_TA_MIDDLE_NEIGHBOURING_GRAY_TONE_DIFFERENCE_MATRIX,
	STR_TA_MIDDLE_GRAY_LEVEL_DEPENDENCE_MATRIX,

	// MINOR
	// 1-1
	STR_TA_SB3D_MESH_VOLUME,
	STR_TA_SB3D_VOXEL_VOLUME,
	STR_TA_SB3D_SURFACE_AREA,
	STR_TA_SB3D_SURFACE_AREA_TO_VOLUME_RATIO,
	STR_TA_SB3D_SPHERICITY,
	STR_TA_SB3D_COMPACTNESS_1,
	STR_TA_SB3D_COMPACTNESS_2,
	STR_TA_SB3D_SPHERICAL_DISPROPORTION,
	STR_TA_SB3D_MAXIMUM_3D_DIAMETER,
	STR_TA_SB3D_MAXIMUM_2D_DIAMETER_SLICE,
	STR_TA_SB3D_MAXIMUM_2D_DIAMETER_COLUMN,
	STR_TA_SB3D_MAXIMUM_2D_DIAMETER_ROW,
	STR_TA_SB3D_MAJOR_AXIS_LENGTH,
	STR_TA_SB3D_MINOR_AXIS_LENGTH,
	STR_TA_SB3D_LEAST_AXIS_LENGTH,
	STR_TA_SB3D_ELONGATION,
	STR_TA_SB3D_FLAATNESS,
	// 1-2
	//STR_TA_SB2D_SPHERICAL_DISPROPORTION,
	STR_TA_SB2D_MESH_SURFACE,
	STR_TA_SB2D_PIXEL_SURFACE,
	STR_TA_SB2D_PERIMETER,
	STR_TA_SB2D_PERIMETER_TO_SURFACE_RATIO,
	STR_TA_SB2D_SPHERICITY,
	STR_TA_SB2D_MAXIMUM_2D_DIAMETER,
	STR_TA_SB2D_MAJOR_AXIS_LENGTH,
	STR_TA_SB2D_MINOR_AXIS_LENGTH,
	STR_TA_SB2D_ELONGATION,
	// 2-1
	STR_TA_FOS_ENERGY,
	STR_TA_FOS_TOTAL_ENERGY,
	STR_TA_FOS_ENTROPY,
	STR_TA_FOS_MINIMUM,
	STR_TA_FOS_10TH_PERCENTILE,
	STR_TA_FOS_90TH_PERCENTILE,
	STR_TA_FOS_MAXIMUM,
	STR_TA_FOS_MEAN,
	STR_TA_FOS_MEDIAN,
	STR_TA_FOS_INTERQUARTILE_RANGE,
	STR_TA_FOS_RANGE,
	STR_TA_FOS_MEAN_ABSOLUTE_DEVIATION_MAD,
	STR_TA_FOS_ROBUST_MEAN_ABSOLUTE_DEVIATION_rMAD,
	STR_TA_FOS_ROOT_MEAN_SQUARED_RMS,
	STR_TA_FOS_STANDARD_DEVIATION,
	STR_TA_FOS_SKEWNESS,
	STR_TA_FOS_KURTOSIS,
	STR_TA_FOS_VARIANCE,
	STR_TA_FOS_UNIFORMITY,
	// 3-1
	STR_TA_GLCM_AUTOCORRELATION,
	STR_TA_GLCM_JOINT_AVERAGE,
	STR_TA_GLCM_CLUSTER_PROMINENCE,
	STR_TA_GLCM_CLUSTER_SHADE,
	STR_TA_GLCM_CLUSTER_TENDENCY,
	STR_TA_GLCM_CONTRAST,
	STR_TA_GLCM_CORRELATION,
	STR_TA_GLCM_DIFFERENCE_AVERAGE,
	STR_TA_GLCM_DIFFERENCE_ENTROPY,
	STR_TA_GLCM_DIFFERENCE_VARIANCE,
	STR_TA_GLCM_JOINT_ENERGY,
	STR_TA_GLCM_JOINT_ENTROPY,
	STR_TA_GLCM_INFORMATIONAL_MEASURE_OF_CORRELATION_IMC_1,
	STR_TA_GLCM_INFORMATIONAL_MEASURE_OF_CORRELATION_IMC_2,
	STR_TA_GLCM_INVERSE_DIFFERENCE_MOMENT_IDM,
	STR_TA_GLCM_MAXIMAL_CORRELATION_COEFFICIENT_MCC,
	STR_TA_GLCM_INVERSE_DIFFERENCE_MOMENT_NORMALIZED_IDMN,
	STR_TA_GLCM_INVERSE_DIFFERENCE_ID,
	STR_TA_GLCM_INVERSE_DIFFERENCE_NORMALIZED_IDN,
	STR_TA_GLCM_INVERSE_VARIANCE,
	STR_TA_GLCM_MAXIMUM_PROBABILITY,
	STR_TA_GLCM_SUM_AVERAGE,
	STR_TA_GLCM_SUM_ENTROPY,
	STR_TA_GLCM_SUM_OF_SQUARES,
	// 3-2
	STR_TA_GLRLM_SHORT_RUN_EMPHASIS_SRE,
	STR_TA_GLRLM_LONG_RUN_EMPHASIS_LRE,
	STR_TA_GLRLM_GRAY_LEVEL_NON_UNIFORMITY_GLN,
	STR_TA_GLRLM_GRAY_LEVEL_NON_UNIFORMITY_NORMALIZED_GLNN,
	STR_TA_GLRLM_RUN_LENGTH_NON_UNIFORMITY_RLN,
	STR_TA_GLRLM_RUN_LENGTH_NON_UNIFORMITY_NORMALIZED_RLNN,
	STR_TA_GLRLM_RUN_PERCENTAGE_RP,
	STR_TA_GLRLM_GRAY_LEVEL_VARIANCE_GLV,
	STR_TA_GLRLM_RUN_VARIANCE_RV,
	STR_TA_GLRLM_RUN_ENTROPY_RE,
	STR_TA_GLRLM_LOW_GRAY_LEVEL_RUN_EMPHASIS_LGLRE,
	STR_TA_GLRLM_HIGH_GRAY_LEVEL_RUN_EMPHASIS_HGLRE,
	STR_TA_GLRLM_SHORT_RUN_LOW_GRAY_LEVEL_EMPHASIS_SRLGLE,
	STR_TA_GLRLM_SHORT_RUN_HIGH_GRAY_LEVEL_EMPHASIS_SRHGLE,
	STR_TA_GLRLM_LONG_RUN_LOW_GRAY_LEVEL_EMPHASIS_LRLGLE,
	STR_TA_GLRLM_LONG_RUN_HIGH_GRAY_LEVEL_EMPHASIS_LRHGLE,
	// 3-3
	STR_TA_GLSZM_SMALL_AREA_EMPHASIS_SAE,
	STR_TA_GLSZM_LARGE_AREA_EMPHASIS_LAE,
	STR_TA_GLSZM_GRAY_LEVEL_NON_UNIFORMITY_GLN,
	STR_TA_GLSZM_GRAY_LEVEL_NON_UNIFORMITY_NORMALIZED_GLNN,
	STR_TA_GLSZM_SIZE_ZONE_NON_UNIFORMITY__SZN,
	STR_TA_GLSZM_SIZE_ZONE_NON_UNIFORMITY_NORMALIZED_SZNN,
	STR_TA_GLSZM_ZONE_PERCENTAGE_ZP,
	STR_TA_GLSZM_GRAY_LEVEL_VARIANCE_GLV,
	STR_TA_GLSZM_ZONE_VARIANCE_ZV,
	STR_TA_GLSZM_ZONE_ENTROPY_ZE,
	STR_TA_GLSZM_LOW_GRAY_LEVEL_ZONE_EMPHASIS_LGLZE,
	STR_TA_GLSZM_HIGH_GRAY_LEVEL_ZONE_EMPHASIS_HGLZE,
	STR_TA_GLSZM_SMALL_AREA_LOW_GRAY_LEVEL_EMPHASIS_SALGLE,
	STR_TA_GLSZM_SMALL_AREA_HIGH_GRAY_LEVEL_EMPHASIS_SAHGLE,
	STR_TA_GLSZM_LARGE_AREA_LOW_GRAY_LEVEL_EMPHASIS_LALGLE,
	STR_TA_GLSZM_LARGE_AREA_HIGH_GRAY_LEVEL_EMPHASIS_LAHGLE,
	// 3-4
	STR_TA_NGTDM_COARSENESS,
	STR_TA_NGTDM_CONTRAST,
	STR_TA_NGTDM_BUSYNESS,
	STR_TA_NGTDM_COMPLEXITY,
	STR_TA_NGTDM_STRENGTH,
	// 3-5
	STR_TA_GLDM_SMALL_DEPENDENCE_EMPHASIS_SDE,
	STR_TA_GLDM_LARGE_DEPENDENCE_EMPHASIS_LDE,
	STR_TA_GLDM_GRAY_LEVEL_NON_UNIFORMITY_GLN,
	STR_TA_GLDM_DEPENDENCE_NON_UNIFORMITY_DN,
	STR_TA_GLDM_DEPENDENCE_NON_UNIFORMITY_NORMALIZED_DNN,
	STR_TA_GLDM_GRAY_LEVEL_VARIANCE_GLV,
	STR_TA_GLDM_DEPENDENCE_VARIANCE_DV,
	STR_TA_GLDM_DEPENDENCE_ENTROPY_DE,
	STR_TA_GLDM_LOW_GRAY_LEVEL_EMPHASIS_LGLE,
	STR_TA_GLDM_HIGH_GRAY_LEVEL_EMPHASIS_HGLE,
	STR_TA_GLDM_SMALL_DEPENDENCE_LOW_GRAY_LEVEL_EMPHASIS_SDLGLE,
	STR_TA_GLDM_SMALL_DEPENDENCE_HIGH_GRAY_LEVEL_EMPHASIS_SDHGLE,
	STR_TA_GLDM_LARGE_DEPENDENCE_LOW_GRAY_LEVEL_EMPHASIS_LDLGLE,
	STR_TA_GLDM_LARGE_DEPENDENCE_HIGH_GRAY_LEVEL_EMPHASIS_SDHGLE,

	// login
	STR_LOGIN,
	STR_LOGIN_ID,
	STR_LOGIN_PWD,
	STR_LOGIN_IDSAVE,
	STR_LOGIN_AUTO,
	STR_LOGIN_DUPLICATE,
	STR_LOGIN_NETWORK_TIMEOUT,

	// For Visual Print
	STR_VISUAL_PRINT,
	STR_VISUAL_PRINT_WEB_LINK,
	//	STR_INFO_DIALOG,
	STR_VISUAL_PRINT_DIALOG,
	STR_VISUAL_PRINT_PREVIEW_SURFACE,

	STR_SELECT_SLICE_DIRECTIVE_SINGLE,
	STR_SELECT_SLICE_DIRECTIVE_MULTI,

	// Error Case
	STR_NONMANIFOLD_HEDGE_CASE,

	// Erro Message 항목
	// DU-1
	ERR_DU_1001,
	ERR_DU_1002,
	ERR_DU_1003,
	ERR_DU_1004,
	ERR_DU_1005,
	ERR_DU_1006,
	ERR_DU_1007,
	ERR_DU_1008,
	ERR_DU_1009,
	ERR_DU_1010,
	ERR_DU_1011,
	ERR_DU_1012,
	ERR_DU_1013,
	ERR_DU_1014,
	ERR_DU_1015,
	ERR_DU_1016_STR_ALREADY_EXIST_THREAD,
	ERR_DU_1017,
	ERR_DU_1018,
	ERR_DU_1019,

	// DU-0
	ERR_DU_0001,
	ERR_DU_0002,
	ERR_DU_0003,
	ERR_DU_0004,
	ERR_DU_0005,
	ERR_DU_0006,
	ERR_DU_0007,

	// DE-0
	ERR_DE_0001,
	ERR_DE_0002,
	ERR_DE_0003,
	ERR_DE_0004,
	ERR_DE_0005,	// -> deepinsthink.dll 에서 나옴
	ERR_DE_0006,
	ERR_DE_0007,
	ERR_DE_0008,
	ERR_DE_0009,
	// DH-0
	ERR_DH_0001,
	ERR_DH_0002,
	ERR_DH_0003,
	ERR_DH_0004,
	ERR_DH_0005,
	ERR_DH_0006,
	ERR_DH_0007,
	ERR_DH_0008,
	// DR-0
	ERR_DR_0001,
	ERR_DR_0002,
	ERR_DR_0003,
	ERR_DR_0004,

	// information


	// error
	//SOPClassUID
	STR_UID_SECONDARY_CAPTUREIMAGE_STORAGE,
};

enum LOCALE
{
	KOREAN = 1,
	ENGLISH,

};


class LocMap
{
public:
	LocMap() { loc = ENGLISH; rstr = STR_OPEN; }
public:
	LOCALE loc;
	RSTRING rstr;
};

class StringManager : public QObject
{
	Q_OBJECT
public:
	static LocMap locMap;
	static StringManager* getSingleton();

public:
	StringManager();
	~StringManager();

	bool Initialize(const QString& sessionName = "");

	bool init();
	void clear();

	QString getString(RSTRING str_type, LOCALE loc = ENGLISH);
	QString getStringFormat(RSTRING str_type, QStringList args, LOCALE loc = ENGLISH);

	QString GetSessionName() const;


public:
	QString programPath;

	QString configFileName;
	QString presetFileName;
	QString localPresetFileName;
	QString presetFilePath;
	QString localPresetFilePath;
	QVector<QString> presetFilePathVec;

	// programfiles 경로
	QString AIFilePath;
	QString AISegmentationPath;
	QString AITranslationPath;
	QString AIClassificationPath;
	QString AIReconstructionPath;
	QString ProgramPathLicenseDirPath;
	QString ProgramPathFunctionLevelDirPath;

	QString m_strAppDataLocalPath;
	QString m_strAppDataLocalAIPath;

	// appdata 경로
	QString LocalAISegPath;		// AI segmentation	
	QString m_strLocalAISegPredictPath;
	QString m_strLocalAISegWeightPath;
	QString m_strLocalAISegUserWeightPath;	// user driven

	QString m_strLocalAITransPath;		// AI translation
	QString m_strLocalAIClassPath;		// AI Classification

	QString m_strLocalLogPath;			// log 저장 위치.
	QString LocalLicenseDirPath;		// license file들 저장 위치.	
	////

	QString config_Layer2DAlpha;
	QString config_LatestPath;
	QString config_SegDockArea;
	QString config_cachePath;
	QString config_expertReportPath;
	QString config_DockTop;
	QString config_DockShow;
	QString config_RenderDockArea;
	QString config_ToolArea;
	QString config_cusWidth;
	QString config_cusLevel;
	QString config_gamma;
	QString config_rePos;
	QString config_wheelZoom;
	QString config_backfaceCulling;
	QString config_shader_quality;
	QString config_3dAnno;
	QString config_imageListShow;
	QString config_cusPreset;
	QString config_cusPreset_AppData;
	QString config_expandROI;
	QString config_expandMesh;
	QString config_color2D;
	QString config_invertingLUT;
	QString config_undoLimit;
	QString config_recentFile;
	QString config_VolumeOpacity3D;
	QString config_RegionGrowingConnectivity;
	QString config_DrawCutShape;

	QString config_BrushThickness;
	QString config_BrushOpacity;

	QString config_autoSave;
	QString config_autoSaveInterval;

	QString config_visualPrintURL;
	QString config_visualPrintPort;

	QString config_MDBOX_Mode;

	QString fontFileName;

	QString cacheFilePath;
	QString m_strTempFilePath;
	QString expertReportFilePath;
	QString dumpFilePath;
	QString cacheFileOriginVolume;

	QString resourceFile;
	QString resourceDir;

	QString license_incode_file;
	QString license_decode_file;

	QString dxSahderAsmFile;

	QString report_format;
	QString localReport_format;
	std::vector<QString> report_basic_formats;

	QMap<RSTRING, QString> strList;

	QString config_lastExecutedTime;
	QString config_SavedID;

	// DeepCatch
	QString m_config_DeepCatch_Project;
	QString m_config_DeepCatch_Predict_UNET;
	QString m_config_DeepCatch_Contrast;
	QString m_config_DeepCatch_AWPredict;
	QString m_config_DeepCatch_AdditionalOptions;
	QString m_config_DeepCatch_PreferenceForReporting;
	QString m_config_DeepCatch_IOClassificationPredict;

	//SUPPORT_DEEPCATCH_VERSION_2
	QString m_config_DeepCatch_BodyComposition;
	QString m_config_DeepCatch_BoneAnalysis;
	QString m_config_DeepCatch_IO_Network;	// 0: liver/spleen, 1: aorta, 2: both, 3: nothing

	QString m_config_DeepCatch_SingleSlice;
	QString m_config_DeepCatch_MultiSliceUp;
	QString m_config_DeepCatch_MultiSliceLow;

	QString m_config_DeepCatch_MuslceQualityMap;

	QString m_config_DeepCatch_SelectionDlg_PositionX;
	QString m_config_DeepCatch_SelectionDlg_PositionY;

	QString Omniverse_AppData_DirectoryPath_Root;
	QString Omniverse_AppData_DirectoryPath_Preset;

	QString OmniverseMaterialDirectoryPath;
	QString OmniverseMaterialDirectoryPath_Preset;

	QString OmniverseConfigJsonFilePath;

private:
	QString m_sessionName;
};


#define STRING_MANAGER StringManager::getSingleton()
#endif