#include "stdafx.h"
#include "filemanager/appcore/Resource/ResourceManager.h"

#ifdef _DEBUG
#pragma comment(lib,"dcmdata.lib")
#pragma comment(lib,"dcmnet.lib")
#pragma comment(lib,"dcmtls.lib")
#pragma comment(lib,"dcmimgle.lib")
#pragma comment(lib,"dcmimage.lib")
#pragma comment(lib,"dcmjpeg.lib")
#pragma comment(lib,"ijg8.lib")
#pragma comment(lib,"ijg12.lib")
#pragma comment(lib,"ijg16.lib")
#pragma comment(lib,"i2d.lib")
#pragma comment(lib,"dcmjpls.lib")
#pragma comment(lib,"dcmtkcharls.lib")
#pragma comment(lib,"ofstd.lib")
#pragma comment(lib,"oflog.lib")
#pragma comment(lib,"ws2_32.lib")
#pragma comment(lib,"iphlpapi.lib")
#pragma comment(lib,"wsock32.lib")
#pragma comment(lib,"netapi32.lib")
#pragma comment(lib,"FileManagerStdd.lib")
#pragma comment(lib,"mipDicom.lib")
#pragma comment(lib,"qpdf.lib")
#pragma comment(lib,"mipEngine.lib")

#pragma comment(lib, "Ws2_32.lib")
#pragma comment(lib, "Netapi32.lib")
#pragma comment(lib, "iphlpapi.lib")
#pragma comment(lib, "Rpcrt4.lib")

#pragma comment(lib, "gdcmcharls.lib")
#pragma comment(lib, "gdcmCommon.lib")
#pragma comment(lib, "gdcmDICT.lib")
#pragma comment(lib, "gdcmDSED.lib")
#pragma comment(lib, "gdcmexpat.lib")
#pragma comment(lib, "gdcmgetopt.lib")
#pragma comment(lib, "gdcmIOD.lib")
#pragma comment(lib, "gdcmjpeg8.lib")
#pragma comment(lib, "gdcmjpeg12.lib")
#pragma comment(lib, "gdcmjpeg16.lib")
#pragma comment(lib, "gdcmmd5.lib")
#pragma comment(lib, "gdcmMEXD.lib")
#pragma comment(lib, "gdcmMSFF.lib")
#pragma comment(lib, "gdcmopenjp2.lib")
#pragma comment(lib, "gdcmzlib.lib")
#else
#pragma comment(lib,"dcmdata.lib")
#pragma comment(lib,"dcmnet.lib")
#pragma comment(lib,"dcmtls.lib")
#pragma comment(lib,"dcmimgle.lib")
#pragma comment(lib,"dcmimage.lib")
#pragma comment(lib,"dcmjpeg.lib")
#pragma comment(lib,"ijg8.lib")
#pragma comment(lib,"ijg12.lib")
#pragma comment(lib,"ijg16.lib")
#pragma comment(lib,"i2d.lib")
#pragma comment(lib,"dcmjpls.lib")
#pragma comment(lib,"dcmtkcharls.lib")
#pragma comment(lib,"ofstd.lib")
#pragma comment(lib,"oflog.lib")
#pragma comment(lib,"ws2_32.lib")
#pragma comment(lib,"iphlpapi.lib")
#pragma comment(lib,"wsock32.lib")
#pragma comment(lib,"netapi32.lib")
#pragma comment(lib,"FileManagerStd.lib")
#pragma comment(lib,"mipDicom.lib")
#pragma comment(lib,"qpdf.lib")
#pragma comment(lib,"mipEngine.lib")

#pragma comment(lib, "Ws2_32.lib")
#pragma comment(lib, "Netapi32.lib")
#pragma comment(lib, "iphlpapi.lib")
#pragma comment(lib, "Rpcrt4.lib")

#pragma comment(lib, "gdcmcharls.lib")
#pragma comment(lib, "gdcmCommon.lib")
#pragma comment(lib, "gdcmDICT.lib")
#pragma comment(lib, "gdcmDSED.lib")
#pragma comment(lib, "gdcmexpat.lib")
#pragma comment(lib, "gdcmgetopt.lib")
#pragma comment(lib, "gdcmIOD.lib")
#pragma comment(lib, "gdcmjpeg8.lib")
#pragma comment(lib, "gdcmjpeg12.lib")
#pragma comment(lib, "gdcmjpeg16.lib")
#pragma comment(lib, "gdcmmd5.lib")
#pragma comment(lib, "gdcmMEXD.lib")
#pragma comment(lib, "gdcmMSFF.lib")
#pragma comment(lib, "gdcmopenjp2.lib")
#pragma comment(lib, "gdcmzlib.lib")
#endif