#pragma once

#include "defineMEDIP.h"

enum ACTION_PROCESSING
{
	ACTP_NONE = 0,
	ACTP_MARKING,
	ACTP_UNMARKING,
	ACTP_REGION_GROWING,
	ACTP_THRESHOLD_SEL,
	ACTP_IMAGE_EROSION,
	ACTP_IMAGE_DILATION,
	ACTP_IMAGE_MOVE,
	ACTP_IMAGE_COMPONENT_CHOISE,
	ACTP_IMAGE_HOLE_FILLING,
	ACTP_IMAGE_VESSELNESS,
	ACTP_IMAGE_FISSURENESS,
	ACTP_IMAGE_FEATUREADD,
	ACTP_GMM_EXTRACTMASK,		//220315 허 건 과장(심장 솔루션)
	ACTP_IMAGE_SUBFEATUREADD,
	ACTP_IMAGE_ENHANCE,
	ACTP_IMAGE_GAUSSIAN,
	ACTP_IMAGE_LAPLACIAN,
	ACTP_IMAGE_BOUNDARY,
	ACTP_IMAGE_CIRCUMFERENCE,
	ACTP_ROLYROI,
	ACTP_ROLYROI_DEL,
	ACTP_FREEDRAWROI,
	ACTP_FREEDRAWROI_DEL,
	ACTP_SKETCHDRAW_SEGMENT,
	ACTP_LEVELSET,
	ACTP_FTP_UPLOAD,
	ACTP_EXPORT_SURFACE,
	ACTP_SAVE_STLFILE,
	ACTP_SAVE_OBJFILE,
	ACTP_SAVE_VTKFILE,
	ACTP_SAVE_3MFFILE,
	ACTP_SAVE_ROI_NIIFILE,
	ACTP_SAVE_NIIFILE,
	ACTP_SAVE_NRRDFILE,
	ACTP_SAVE_TXTFILE,
	ACTP_SAVE_RAWFILE,
	ACTP_SAVE_HURAWFILE,
	ACTP_SAVE_MIPFILE,
	ACTP_SAVE_JSONFILE,
	ACTP_OPEN_DICOMFILE,
	ACTP_OPEN_MIPFILE,
	ACTP_OPEN_NIIFILE,
	ACTP_OPEN_PRDFILE,
	ACTP_OPEN_RAWFILE,
	ACTP_OPEN_ROIFILE,
	ACTP_OPEN_TXTFILE,
	ACTP_OPEN_STLFILE,
	ACTP_OPEN_OBJFILE,
	ACTP_OPEN_VTKFILE,
	ACTP_OPEN_USDFILE,
	ACTP_OPEN_3MFFILE,
	ACTP_OPEN_IMGFILE,
	ACTP_CALC_MATCHINGDATA,
	ACTP_FREEDRAW_DRAW_3D,
	ACTP_FREEDRAW_DEL_3D,
	ACTP_IMAGE_ISOTROPIC,
	ACTP_IMAGE_ISOTROPIC_MODIFICATION,	// spacing < 1mm 일 경우 resolution을 변경
	ACTP_IMAGE_SCALE,
	ACTP_IMAGE_CROP,
	ACTP_INTER_DRAW,
	ACTP_INTER_DEL,
	ACTP_TEXTUREFEATURE_TO_REPORT,
	ACTP_INTER_ANGLED_DRAW,
	ACTP_INTER_ANGLED_DEL,
	ACTP_CUDA_LIVER_ADD,
	ACTP_SPLIT_3D,
	ACTP_SPLIT_FILE,
	ACTP_DEEP_DRAW_TRAIN,			// segmentation
	ACTP_DEEP_DRAW_PREDICT,
	ACTP_AI_TRANSLATION_PREDICT,	// tranlation	
	ACTP_AI_CONTRAST_SYNTHESIS_PREDICT,	// contrast synthesis	
	ACTP_CLASSIFICATION_PREDICT,	// classification
	ACTP_AI_KERNEL_CONTINOUS_CONVERSION_PREDICT,	// kernel conversion
	ACTP_AI_KERNEL_NEUTRALIZATION_CONVERSION_PREDICT,	// kernel neutralization	
	ACTP_AI_LOWDOSE_RECONSTRUCTION_PREDICT,	// lowdose reconstruction
	ACTP_AI_CT_QUANTIZATION_PREDICT,	// lowdose reconstruction

	// covid19
	ACTP_COVID19_FEATURE_TO_REPORT,
	ACTP_COVID19_PREDICT,
	// DeepCatch New
	ACTP_L3_PREDICT,
	ACTP_L3_USERSELECT,
	ACTP_ABDOMIAL_WAIST_RANGE,				// 알고리즘으로 찾음
	ACTP_ABDOMIAL_WAIST_RANGE_PREDICT,		// 트레이닝 데이터로 찾음
	ACTP_ABDOMIAL_WAIST_USERSELECT,
	ACTP_SAVE_3D_VOLUME,
	ACTP_DEEPCATCH_REPORT,
	ACTP_DEEPCATCH_BONE2VB_PREDICT,				//202204_byPHS  out - Vertebra
	ACTP_DEEPCATCH_VB2IND_PREDICT,				//202205_byPHS  out - L1-L6, T1-T12, T13
	ACTP_DEEPCATCH_VB2BMCB_PREDICT,				//202205_byPHS	out - Bone marrow, Cortical bone
	ACTP_DEEPCATCH_DEL_MASK_POSTERIOR,			//202204_byPHS
	ACTP_DEEPCATCH_FIND_PICK_MASKNAME,			//202204_byPHS
	ACTP_DEEPCATCH_IO_AORTA,					//202206_byPHS
	ACTP_DEEPCATCH_IO_LIVER_SPLEEN,				//202206_byPHS
	ACTP_DEEPCATCH_HCC_PREDICT,				//202206_byPHS

	ACTP_AI_GMM_EXRACTMASK,					// Extract mask usnig GMM Process (220408 허 건 과장, 심장솔루션)

	// mesh
	ACTP_MESH_PLANE_CUT,
	ACTP_MESH_POLYGON_CUT,
	ACTP_MESH_POLYLINE_CUT,
	ACTP_MESH_FREEPOLY_CUT,
	ACTP_MESH_ATTACH,
	ACTP_MESH_DUPLICATE,
	ACTP_MESH_SUBDIVISION,
	ACTP_MESH_ISLANDFILTER,
	ACTP_MESH_BOOLEAN,
	ACTP_MESH_ALIGN,
	ACTP_MESH_STAMP3D,
	ACTP_MESH_REMESH,//Including solid, hollow, reduction
	ACTP_MESH_SMOOTH,
	ACTP_MESH_DATA_CHANGED,
	ACTP_MESH_LAYER_VISIBILITY_CHANGED,
	ACTP_MESH_LAYER_COLOR_CHANGED,
	ACTP_MESH_LAYER_NAME_CHANGED,
	ACTP_MESH_LAYER_MATERIAL_CHANGED,
	ACTP_MESH_LAYER_LOCK_CHANGED,

	//radiomic
	ACTP_CALCULATE_FEATURE,
	ACTP_CALCULATE_3D_FEATURE,
	// visual print
	ACTP_VISUAL_PRINT_PREVIEW_SURFACE,
	ACTP_VISUAL_PRINT_SAVE_MESH,
	ACTP_VISUAL_PRINT_UPLOAD,
	ACTP_VISUAL_PRINT_UPLOAD_ROI,
	ACTP_VISUAL_PRINT_WEB_LINK,
	ACTP_VISUAL_PRINT_DIALOG,

	ACTP_MASK_LIST_SPLIT_REGION,
	ACTP_MASK_LIST_IMAGE_CALCULATE,
	ACTP_MASK_LIST_3D_INTERPOLATION,

	ACTP_TEST
};

enum DEEPCATCH_MACRO_TYPE
{
	eDMTDefault,				// default : trunk predict를 제외한 기본 predict + report 처리.
	eDMTReportOnly,				// predict 제외하고 report만 진행.
	eDMTTrunkPredictAdd,		// trunk predict mode : deepcatch predict -> trunk predict
	eDMTQCTPredictAdd,			// qct precict mode : qct predict -> deepcatch predict
};

enum DEEPCATCH_ADDITIONAL_MACRO_TYPE
{
	eDAMTNone,					// DEEPCATCH_MACRO_TYPE만 사용.
	//	eDAMTMuscleClassification,	// Muscle을 4가지 타입으로 추가 분류.
};

