#pragma once

#define MEDIP_AI_CT_AIRWAY ("CT_Airway")
#define MEDIP_AI_CT_ARMTRUNK2D ("CT_ArmTrunk2D")
#define MEDIP_AI_CT_ARMTRUNK3D ("CT_ArmTrunk3D")
#define MEDIP_AI_CT_BODY_CHEST ("CT_Body (Chest)")
#define MEDIP_AI_CT_BONE_CHEST ("CT_Bone (Chest)")
#define MEDIP_AI_CT_HEPATICVESSEL_TUMOR ("CT_HepaticVessel,Tumor")
#define MEDIP_AI_CT_LIVER_TUMOR ("CT_Liver Tumor")
#define MEDIP_AI_CT_LIVER_TUMOR_2 ("CT_Liver,Tumor")
#define MEDIP_AI_CT_PANCREAS_TUMOR ("CT_Pancreas,Tumor")
#define MEDIP_AI_CT_WHOLEBODY_CON_2D ("CT_WholeBody (Con)2D")
#define MEDIP_AI_CT_WHOLEBODY_CON_3D ("CT_WholeBody (Con)3D")
#define MEDIP_AI_CT_WHOLEBODY_NON_2D ("CT_WholeBody (Non)2D")
#define MEDIP_AI_CT_WHOLEBODY_NON_3D ("CT_WholeBody (Non)3D")
#define MEDIP_AI_CT_EPICARDIALCON ("CT_EpicardialCon")
#define MEDIP_AI_CT_EPICARDIALNON ("CT_EpicardialNon")
#define MEDIP_AI_CT_LUNG_TUMOR ("CT_Lung Tumor")
#define MEDIP_AI_MR_SKULL_3DNN_ADDIN ("MR_Skull_3DNN_Addin")
#define MEDIP_AI_MR_MENINGIOMA_2DNN_ADDIN ("MR_Meningioma_2DNN_Addin")
#define MEDIP_AI_MR_MENINGIOMA_2DNNATT_ADDIN ("MR_Meningioma_2DNNATT_Addin")
#define MEDIP_AI_MR_MENINGIOMA_3DNN_ADDIN ("MR_Meningioma_3DNN_Addin")
#define MEDIP_AI_MR_MENINGIOMA_2D_ADDIN ("MR_Meningioma_2D_Addin")
#define MEDIP_AI_MR_MENINGIOMA_2DATT_ADDIN ("MR_Meningioma_2DATT_Addin")
#define MEDIP_AI_MR_MENINGIOMA_ATTENTION_NNUNET ("MR_Meningioma_Attention_nnUNet")
#define MEDIP_AI_MR_MENINGIOMA_ATTENTION_UNET ("MR_Meningioma_Attention_UNet")
#define MEDIP_AI_MR_MENINGIOMA_2D_UNET ("MR_Meningioma_2D_UNet")
#define MEDIP_AI_MR_MENINGIOMA_3D_UNET ("MR_Meningioma_3D_UNet")
#define MEDIP_AI_MR_MENINGIOMA_2D_NNUNET ("MR_Meningioma_2D_nnUNet")
#define MEDIP_AI_MR_MENINGIOMA_3D_NNUNET ("MR_Meningioma_3D_nnUNet")
#define MEDIP_AI_CT_LIVER_NON ("CT_Liver (Non)")
#define MEDIP_AI_CT_LIVER_PORTAL ("CT_Liver (Portal)")
#define MEDIP_AI_CT_LUNG ("CT_Lung")
#define MEDIP_AI_CT_PULMONARY_CON_3D ("CT_Pulmonary (Con)3D")
#define MEDIP_AI_CT_PULMONARY_NON_3D ("CT_Pulmonary (Non)3D")
#define MEDIP_AI_CT_SPLEEN ("CT_Spleen")
#define MEDIP_AI_CT_THYROID ("CT_Thyroid")
#define MEDIP_AI_CT_TRUNK_QCT ("CT_Trunk(QCT)")
#define MEDIP_AI_CT_THYROID_3DNN_ADDIN ("CT_Thyroid_3DNN_Addin")
#define MEDIP_AI_CT_MUSCLECHEST_3DNN_ADDIN ("CT_MuscleChest_3DNN_Addin")
#define MEDIP_AI_CT_CAVITY3D ("CT_Cavity3D")
#define MEDIP_AI_CT_COVID19 ("CT_COVID19")
#define MEDIP_AI_CT_LUNG_FISSURE_LOBE3D ("CT_Lung Fissure, Lobe3D")
#define MEDIP_AI_CT_LUNG_LESION ("CT_Lung Lesion")
#define MEDIP_AI_CT_BO2D_ADDIN ("CT_BO2D_Addin")
#define MEDIP_AI_CT_BO3D_ADDIN ("CT_BO3D_Addin")
#define MEDIP_AI_CT_COVID19_3DNN ("CT_COVID19_3DNN")
#define MEDIP_AI_CT_BO2DNN_ADDIN ("CT_BO2DNN_Addin")
#define MEDIP_AI_CT_BO3DNN_ADDIN ("CT_BO3DNN_Addin")
#define MEDIP_AI_CT_PS_3DNN_ADDIN ("CT_PS_3DNN_Addin")
#define MEDIP_AI_CT_HEART_3DNN ("CT_Heart_3DNN")
#define MEDIP_AI_CT_HEARTVM_3DNN ("CT_HeartVM_3DNN")
#define MEDIP_AI_CT_HEART_SOLUTION ("CT_Heart_Solution")

extern const char* MEDIP_AI_PROJECT_NAME_LIST[51];


