#include "stdafx.h"
#include "AIProjectFactory.h"

static std::vector<AIProject> DEFAULT_MEDIP_AI_PROJECT_LIST = {
	AIProject(MEDIP_AI_CT_AIRWAY, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_ARMTRUNK2D, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_ARMTRUNK3D, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_BODY_CHEST, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_BONE_CHEST, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_HEPATICVESSEL_TUMOR, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_LIVER_TUMOR, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_LIVER_TUMOR_2, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_PANCREAS_TUMOR, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_WHOLEBODY_CON_2D, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_WHOLEBODY_CON_3D, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_WHOLEBODY_NON_2D, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_WHOLEBODY_NON_3D, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_EPICARDIALCON, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_EPICARDIALNON, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_CT_LUNG_TUMOR, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),

	AIProject(MEDIP_AI_MR_SKULL_3DNN_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_2DNN_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_2DNNATT_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_3DNN_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_2D_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_2DATT_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_ATTENTION_NNUNET, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_ATTENTION_UNET, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_2D_UNET, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_3D_UNET, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_2D_NNUNET, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(MEDIP_AI_MR_MENINGIOMA_3D_NNUNET, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),

	/* Image Component Choise */
	AIProject(
		{ AIProject(MEDIP_AI_CT_LIVER_NON, ACTP_DEEP_DRAW_PREDICT, THREAD_COMPONENT_CHOICE) },
		MEDIP_AI_CT_LIVER_NON, ACTP_IMAGE_COMPONENT_CHOISE, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LIVER_PORTAL, ACTP_DEEP_DRAW_PREDICT, THREAD_COMPONENT_CHOICE) },
		MEDIP_AI_CT_LIVER_PORTAL, ACTP_IMAGE_COMPONENT_CHOISE, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_COMPONENT_CHOICE) },
		MEDIP_AI_CT_LUNG, ACTP_IMAGE_COMPONENT_CHOISE, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_PULMONARY_CON_3D, ACTP_DEEP_DRAW_PREDICT, THREAD_COMPONENT_CHOICE) },
		MEDIP_AI_CT_PULMONARY_CON_3D, ACTP_IMAGE_COMPONENT_CHOISE, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_PULMONARY_NON_3D, ACTP_DEEP_DRAW_PREDICT, THREAD_COMPONENT_CHOICE) },
		MEDIP_AI_CT_PULMONARY_NON_3D, ACTP_IMAGE_COMPONENT_CHOISE, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_SPLEEN, ACTP_DEEP_DRAW_PREDICT, THREAD_COMPONENT_CHOICE) },
		MEDIP_AI_CT_SPLEEN, ACTP_IMAGE_COMPONENT_CHOISE, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_TRUNK_QCT, ACTP_DEEP_DRAW_PREDICT, THREAD_COMPONENT_CHOICE) },
		MEDIP_AI_CT_TRUNK_QCT, ACTP_IMAGE_COMPONENT_CHOISE, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_THYROID_3DNN_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_COMPONENT_CHOICE) },
		MEDIP_AI_CT_THYROID_3DNN_ADDIN, ACTP_IMAGE_COMPONENT_CHOISE, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_MUSCLECHEST_3DNN_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_COMPONENT_CHOICE) },
		MEDIP_AI_CT_MUSCLECHEST_3DNN_ADDIN, ACTP_IMAGE_COMPONENT_CHOISE, THREAD_NONE),

	/* Lung Filter */
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_CAVITY3D, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_COVID19, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_LUNG_FISSURE_LOBE3D, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_LUNG_LESION, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_BO2D_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_BO3D_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_COVID19_3DNN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_BO2DNN_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_BO3DNN_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),
	AIProject(
		{ AIProject(MEDIP_AI_CT_LUNG, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_PS_3DNN_ADDIN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),

	/* Heart Solution */
	AIProject(MEDIP_AI_CT_HEART_3DNN, ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),

	AIProject(
		{ AIProject(MEDIP_AI_CT_HEART_3DNN, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT) },
		MEDIP_AI_CT_HEARTVM_3DNN , ACTP_DEEP_DRAW_PREDICT, THREAD_NONE),

	AIProject(
		{ 
			AIProject(MEDIP_AI_CT_HEART_3DNN, ACTP_DEEP_DRAW_PREDICT, THREAD_DEEPDRAW_PREDICT),
			AIProject(MEDIP_AI_CT_HEARTVM_3DNN, ACTP_DEEP_DRAW_PREDICT, THREAD_GMM_EXRACTMASK),
		},
		MEDIP_AI_CT_HEART_SOLUTION, ACTP_AI_GMM_EXRACTMASK, THREAD_NONE),
};

std::shared_ptr<AIProjectFactory> AIProjectFactory::NewMEDIP()
{
	std::shared_ptr<AIProjectFactory> pNew = std::make_shared<AIProjectFactory>();

	for (const AIProject& project : DEFAULT_MEDIP_AI_PROJECT_LIST)
	{
		pNew->AddProject(project);
	}

	return pNew;
}

AIProjectFactory::AIProjectFactory()
{
}

bool AIProjectFactory::AddProject(const AIProject& aiProject)
{
	m_AIProjectList.push_back(aiProject);
	return true;
}

bool AIProjectFactory::IsProjectExist(const std::string& projectName) const
{
	auto it = std::find_if(m_AIProjectList.begin(), m_AIProjectList.end(), [projectName](const AIProject& p) {
		return p.GetName() == projectName;
		});
		
	return (it != m_AIProjectList.end());
}

bool AIProjectFactory::IsProjectListExist(const std::vector<std::string>& projectNameList) const
{
	for (auto& name : projectNameList)
	{
		if (IsProjectExist(name) == false)
		{
			return false;
		}
	}
	return true;
}

std::vector<AIProject> AIProjectFactory::GetProjectList() const
{
	return m_AIProjectList;
}
